### ISSUE TITLE
Fix use of `yarn pack`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1019]
We currently have a folder called `node_modules` in our dist for when a package is built. This folder contains the version of our packages used internally which is needed for components in our library.

We have hit an unfortunate snag where `yarn pack` ignores any folder named `node_modules` when packing, making its tarballs broken. 

Investigate the following options:
- Figure out if we can overwrite this ignore feature in `yarn pack`.
- Maybe rename the built `node_modules` folder to something else?
- If `yarn pack` cant be fixed. Remove the script `pack:react` in our root

**Comment by Barsnes** [comment]
I have been investigating this, and it seems like it is meant to ignore any folders with the name `node_modules`.
As can be seen [here](https://github.com/yarnpkg/yarn/blob/d1d5343082cd5a3b2020962c0bb6f2d6fb1ac4f3/src/cli/commands/pack.js#L28).

It was mentioned in this yarnpkg/yarn#2063 and then again in yarnpkg/yarn#5966, which should have a merged a fix for it, but the fix with `bundledDependencies` does not seem to work today.

As @mimarz mentioned, we should probably remove `yarn pack:react`. `npm pack` **will** contain `node_modules`, so I suggest using that.

**Comment by mimarz** [comment]
Suggest we remove the `pack:react` which uses yarn pack and call it a day.
