### ISSUE TITLE
Skip link: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1054]
See https://design-system.service.gov.uk/components/skip-link/

### Skip link
Skip link kalles også skip navigation link på engelsk og snarvei på norsk. Vi bruker denne komponenten når vi vil hjelpe folk som kun bruker tastaturet til å navigere, slik at de enkelt kan går til de viktigste innholdet på en side.
Snarveien bør være ett av de første elementene markøren går til når du navigerer med tastaturet.

### Retningslinjer for når du skal bruke skip link
Noen brukere navigerer med Tab på tastaturet når de skal flytte markøren forbi lenker eller skjemalementer på en nettside. Når vi inkluderer en snarvei-komponent på siden, får disse brukerne muligheten til å gå forbi alle navigeringslenkene øverst på siden og kan gå direkte til hovedinnholdet på siden.

Ifølge WCAG er det et krav at det skal være med en snarvei-komponent i faste sidemaler til alle nettsteder. Les mer om dette hos Tilsynet. (lenke) 

Vi plasserer snarveien rett etter <body>-koden. Hvis siden har et varsel om informasjonskapsler, legger du skip link rett etter koden for dette varselet.

Snarveien bør skille seg tydelig ut fra resten av innholdet, slik at folk som er seende, men bruker tastaturet til å navigere, kan kjenne igjen dette element før de flytter videre.

### Tekst i komponenten
Pass på at teksten tydelig sier hva snarveien skal brukes til. Bruk en enkel tekst, som for eksempel «Gå direkte til innholdet» «Hopp direkte til innholdet» eller «hopp over navigeringslenkene».

### Tilgjengelighet
Snarvei-komponenten er vanligvis ikke synlig før et trykk på tastaturet aktiverer den.
Snarveien må bli godt synlig når den får fokus.
Teksten på snarveien må ha riktig fargekontrast.

Vær oppmerksom på at noen automatiske tester for tilgjengelighet kan varsle om at snarveien mangler i et landemerke. Dette varslet gjelder ikke for snarveier, så det kan du overse. Pass på at du ikke inkluderer («wrapper») snarveien i et <nav>-område eller flytter den inn i toppteksten/overskriften.

Pass på at snarveier oppfører seg forutsigbart. En snarvei med teksten «Gå direkte til innholdet» skal flytte brukerens fokus til starten på innholdet, ikke til starten av første avsnitt under overskriften.

**Comment by Ildest** [comment]
Tekstforslag levert til @Febakke, som tar stafettpinnen videre og legger alt inn i Figma/Storybook. Det må være den raskest utviklede og beskrevne komponenten noensinne @mrosvik  :-D

**Comment by Ildest** [comment]
Ready for Storybook after review from @Febakke and me.
