### ISSUE TITLE
Breadcrumb: Design component in Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1102]
## Specification and requirements
- Should come in 3 sizes: `Small`, `medium`, `large`. 
- Should use the link-component. 
- Design for small and large screen sizes. 
- A separator should provide clearly distinguishes between each page.

![Image](https://github.com/user-attachments/assets/9f90eb22-8a07-46b9-a444-034dc399f23a)
[Figma](https://www.figma.com/design/vpM9dqqQPHqU6ogfKp5tlr/Designsystemet---Core-UI-Kit?m=auto&node-id=36610-6821&t=luEwc06OfAtYGAV0-1)

**Comment by mrosvik** [comment]
Thanks to @fredrikstorheil for contributing to design of the Breadcrumb component! :clap::skin-tone-2: :star:️ :sports_medal:

**Comment by Thuneer** [comment]
I did a design review and everything looks great! I like that black text is used for the links to avoid problems on colored backgrounds.
