### ISSUE TITLE
Breadcrumb: Develop React component

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1104]
Design at https://www.figma.com/design/vpM9dqqQPHqU6ogfKp5tlr/Designsystemet---Core-UI-Kit?node-id=36610-6819&t=f05IsJp27gNDrbZD-4

**Comment by eirikbacker** [comment]
**Accessibility:**
- Should have structure `<nav><ol><li><a>`
- `<nav>` must have a descriptive `aria-label` (f.eks "Sidens plassering" - not "Breadcrumbs")
- Last link must have `aria-current="page"`
- The visual divider must be hidden from screen readers (note that `content` in `::before` and `::after` is announced by screen readers, unless using the syntax `content: '' / 'Content here'` (not supported by Firefox yet))
