### ISSUE TITLE
Update the Radio and Checkbox design to match Figma

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#1115]
* The gap between the SVG and the text is not correct according to Figma on the different sizes.
  *  Maybe try to make the code more similar Figma by using a gap margin instead of padding-left.

* The border is thicker in code than in Figma.

* Make sure font-size and the SVG icon are the same sizes as in Figma.

![Image](https://github.com/digdir/designsystem/assets/13560642/c67a1200-ef9d-4a6e-b3da-48782c1e4144)

**Comment by Barsnes** [comment]
They both currently use padding `calc(var(--fds-spacing-6) + 17px);`.
It would be better if this was in a `grid` or `flex` container, where we can set a `gap` property.
We should try to avoid any breaking changes when changing the markup

**Comment by mimarz** [comment]
This will be fixed in [#1224](https://github.com/digdir/designsystemet/issues/1224)

**Comment by mrosvik** [comment]
Må bli dobbelsjekket før vi lukker denne.
