### ISSUE TITLE
Bytte `_` med `-` i CSS-variabelnavn i tokens.

### ISSUE THREAD

**Issue by TobiasGunther** [digdir/designsystemet#1123]
### Description

Vår designer bruker Figma Token Studio med fds-tokens for å lage skisser, og når utviklere kopierer CSS-koden generert av Figma blir der miss-match mellom CSS-variabelnavn. Nærmere forklart oppgir Figma DevMode f.eks. `--border-radius-medium` , mens det faktiske variabelnavnet definert i tokens heter `--fds-border_radius-medium`. Problemet med dette er at kopiert CSS-kode fra Figma vil gi CSS som ikke klarer å finne riktige verdier. Vedlagte bilder viser utklipp fra Figma og `tokens.css`.
   
![image](https://github.com/digdir/designsystem/assets/107984787/796b9390-a6c6-46ff-8edf-3627cc3381f8)

![image (1)](https://github.com/digdir/designsystem/assets/107984787/f947ddbd-16ad-4b4d-9b01-64b05089f797)

![image (2)](https://github.com/digdir/designsystem/assets/107984787/35354c7e-77eb-487c-86d2-c1a2aa93cf63)

Siden Figma Token Studio ikke enda har støtte for prefix-ing av variabelnavn må det manuelt legges til `fds` i alle variabelnavn som kommer fra Figmas CSS-kode. Dette ville ha vært en rimelig løsning fram til Figma støtter prefixes, problemet er bruk av `_` i variabelnavn. Dette krever at variabelnavn MÅ undersøkes for bruk av understrek, siden Figma CSS-kode vil alltid bruke `-`. Derfor er det ønskelig at `_` byttes med `-` i fds-toknes slik at Figma CSS-kode fungerer rett ut av boksen (bortsett fra manuell tilføying av `fds`).

**Comment by mimarz** [comment]
Hei og takk for tilbakemeldingen! 

Så kjekt dere bruker tokensa i Figma og kode! 👏 

Du belyser et viktig poeng. Vi må ta en nærmere titt på dette i sin helhelt da en slik endring vil endre navn på alle tokens i css variabler som har understrek i seg, som vil medfører en breaking change. 

Kunne og tenkt meg at vi undersøke nærmere hvilke konfigurasjons-muligheter vi har for disse "suggested variables" til Figma da vi ønsker jo ikke at de skal være førende akkurat 🙈

**Comment by mimarz** [comment]
Fant relevant feature request på Figma forum: https://forum.figma.com/t/ability-to-specify-format-of-variables-code-syntax/51415

**Comment by mrosvik** [comment]
Solved in V1
