### ISSUE TITLE
Modal `autoFocus` sometimes not working

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#1177]
### Description of the bug

There are occurrences of `autoFocus` not working. This needs further investigation.
@jensmo98 discovered this issue, and might be able to provide more information.

First issue covering this bug was #1116

### Steps To Reproduce

Use modal with `autoFocus` set

**Comment by mrosvik** [comment]
@Barsnes Do we know more about this issue?

**Comment by Barsnes** [comment]
> @Barsnes Do we know more about this issue?

Nothing new has been found yet

**Comment by eirikbacker** [comment]
This can happen due to the entrance animation on Modal, it is fixed in #2440
