### ISSUE TITLE
Accordion: Improvements

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1242]
`Accordion` should be updated according to[ the design in Figma](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=20759%3A80555&mode=design&t=jalGJEnvFypaUD0P-1).

```[tasklist]
### Tasks
- [x] https://github.com/digdir/designsystem/issues/1247
- [ ] https://github.com/digdir/designsystem/issues/1248
```

**Comment by mimarz** [comment]
Suggest fixing hoverstate and grayalphas in separate issue when the tokens are available.

**Comment by Barsnes** [comment]
All linked issues are closed, should we close this epic?
