### ISSUE TITLE
Divide button into 2 components in Figma (Button and IconButton)

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1245]
We need a larger icon inside the buttons that only has icon and no text. We should separate the `button`-component with a separate component for `IconButton` (buttons with only icon). This will also make the button component simpler to maintain in Figma. 

Edit: I kode kan det fortsatt være Button. Vi har enkelt måte å detektere når ikonet er satt og om det kun er et ikon. Vi kan  skille dem som to komponenter under Button-siden i Figma.

**Comment by mrosvik** [comment]
@Barsnes  I guess its still relevant for Figma?

**Comment by Barsnes** [comment]
> @Barsnes I guess its still relevant for Figma?

I belive so. In code we solve this with a boolean that changes the styling of the button
