### ISSUE TITLE
Tag: Should be updated according to new Figma design

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1261]
We have received feedback that the `tag` component can be confused with `button`, and we therefore need to make some adjustments.

 - [x] Remove primary (dark) version
- [x] Remove border on light version
- [x] Warning tag should use token: `surface-warning-default` instead of `surface-warning-subtle`

Se simplified version in Figma:

![Image](https://github.com/digdir/designsystem/assets/1464915/1c70f388-3773-4456-ae7a-4214ae1b81e9)

https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=20731%3A71294&mode=design&t=ERiMgvjCjKXewjMw-1

**Comment by mrosvik** [comment]
Is it possible to change the order so `first`, `second`, `third` is placed together?  

![Image](https://github.com/digdir/designsystemet/assets/1464915/01355a4c-b7fe-4574-b758-d7c7b72e15e3)

**Comment by allinox** [comment]
@mrosvik 
I'll fix 😊
