### ISSUE TITLE
Upgrade Storefront to use correct mdx setup

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1266]
We are currently using and old way of setting up next with mdx support. This is preventing us from keeping dependencies up to date and we have very old packages here, meaning it will just get worse as next develops.

- https://mdxjs.com/packages/react/
> If you use Next.js, do not use this. Add an mdx-components.tsx (in src/ or /) file instead. See [Configuring MDX on nextjs.org](https://nextjs.org/docs/pages/building-your-application/configuring/mdx) for more info.

Use this guide for configuring the new way: https://nextjs.org/docs/pages/building-your-application/configuring/mdx

**Comment by Barsnes** [comment]
This was done in the next branch
