### ISSUE TITLE
Update token builder to support $ linking

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1268]
We have used curly brackets (`{token}`) in Token studio for linking to other design tokens but apparently you can now also prepend with dollar-sign (`$token`)  to get the same effect. 

Our token-builder does not support this, this might be due to outdated `@tokens-studio/sd-transforms` which we have planned to update #1269

**Comment by mrosvik** [comment]
@mimarz : We think this was solved with updating token transformer
