### ISSUE TITLE
ErrorSummary: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1319]

**Comment by Ildest** [comment]
Lagt til Word-fil i Teams

**Comment by Ildest** [comment]
Status by 21. March: Draft submitted by Ann-Elisabeth in https://digdir.sharepoint.com/:w:/r/sites/bod-bbo/Delte%20dokumenter/Team%20Designsystem/God%20praksis%20og%20retningslinjer/Komponenter/Error%20summary.docx?d=w3f629e67afcb45608c43dc440635169a&csf=1&web=1&e=f7LuRT
