### ISSUE TITLE
Table: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1343]
```[tasklist]
### Tasks
- [ ] #2281
```

**Comment by Ildest** [comment]
Lagt til Word-fil i Teams

**Comment by Ildest** [comment]
Status 21. March: Draft submitted by Ann-Elisabeth in https://digdir.sharepoint.com/:w:/r/sites/bod-bbo/Delte%20dokumenter/Team%20Designsystem/God%20praksis%20og%20retningslinjer/Komponenter/Table.docx?d=w4d2403d84c904777aee61f42b3595f72&csf=1&web=1&e=fY6k9f
