### ISSUE TITLE
XXLarge headings

### ISSUE THREAD

**Issue by stianmorsund** [digdir/designsystemet#1345]
### Description

For a project we would like a larger version of the heading. This is useful for e.g hero-sections. Also there exists an xxsmall variant, so why not an xxlarge one? :)

Can contribute a PR if you agree. We would need to decide on sizing first

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/1465
- [x] https://github.com/digdir/designsystemet/issues/1481
```

**Comment by mimarz** [comment]
Ahoi! 

Thanks for the request.

We have a typography scale defined in tokens/figma so it would have to be added that way.

We'll have a closer look at this as I assume some might even want bigger headings!

**Comment by mrosvik** [comment]
@stianmorsund 
Our typography scale is currently defined up to f5 (38px/2.38rem). I added a f6 now ([#1374](https://github.com/digdir/designsystemet/pull/1374/files)), which will be 44px/2.75rem. Is this enough for your case or should we add even more levels to the scale? 

![Image](https://github.com/digdir/designsystemet/assets/1464915/b11d707b-385c-4292-b84b-5fa65e642706)

Also, Im not quite sure where to put this size in the semantic set. 
- Should we add it as a xxl heading? In that case, should xl still be the default H1 size? In cases where those big text are used, will it always be headings? 🤔
- Or... should we add a "typography/`hero`" folder for sizes f6, f7, f8, f9...? 🤔

![Image](https://github.com/digdir/designsystemet/assets/1464915/fba249cf-cc99-4ff1-a196-c53c251e91f3)

**Comment by mrosvik** [comment]
Correction: Size f6 will be 43px (not 44).

Her you can se more levels added to the scale and their sizes at different viewports: 



![Image](https://github.com/digdir/designsystemet/assets/1464915/adf45eff-dc9a-4f98-9acf-efdb8ebdd3d8)

**Comment by mrosvik** [comment]
How large should we go? :D

**Comment by mrosvik** [comment]
Here´s an example of an article with 
H1 - f5
H2 - f4
H3 - f3
H4 - f2
H5 - f1
H6 - f0

![Image](https://github.com/digdir/designsystemet/assets/1464915/3d16090b-5cb1-4151-8299-3c1daf67ceea)

**Comment by stianmorsund** [comment]
Hi, thanks for the reply! :)

I have talked to our designer and she says that a minimum of 48px would be great for our use case, so f7 would be the closest. Right now we are using the same clamping function with custom sizings like this:
```(css)
--heading-xxlarge: 500 clamp(1.8rem, calc(1.55vw + 1.8rem), 2.8rem) /1.3 'Inter';
```

Splitting out into a typography/hero-folder might  be useful to avoid the "coupling" with the article typography, since hero sections sometimes use larger fonts. I don't know how normal that is for designsystems though. Looking at gov.uk they have solved this by providing some helper classes for font-sizing: https://design-system.service.gov.uk/styles/typography/#font-override-classes.

**Comment by mimarz** [comment]
> Hi, thanks for the reply! :)
> 
> I have talked to our designer and she says that a minimum of 48px would be great for our use case, so f7 would be the closest. Right now we are using the same clamping function with custom sizings like this:
> 
> ```
> --heading-xxlarge: 500 clamp(1.8rem, calc(1.55vw + 1.8rem), 2.8rem) /1.3 'Inter';
> ```
> 
> Splitting out into a typography/hero-folder might be useful to avoid the "coupling" with the article typography, since hero sections sometimes use larger fonts. I don't know how normal that is for designsystems though. Looking at gov.uk they have solved this by providing some helper classes for font-sizing: https://design-system.service.gov.uk/styles/typography/#font-override-classes.

Thanks for the feedback! We don't have an issue for it yet, but we have talked about providing more utility/helper classes just like [tailwind](https://tailwindcss.com/docs/font-size) and ukgov as you mentioned. Not just typography, but also things like borders, border-radius, spacing etc. 

We'll have a look again at what makes sense, best would be to find a solution that works now and for future needs also :)

**Comment by mimarz** [comment]
> > Hi, thanks for the reply! :)
> > I have talked to our designer and she says that a minimum of 48px would be great for our use case, so f7 would be the closest. Right now we are using the same clamping function with custom sizings like this:
> > ```
> > --heading-xxlarge: 500 clamp(1.8rem, calc(1.55vw + 1.8rem), 2.8rem) /1.3 'Inter';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Splitting out into a typography/hero-folder might be useful to avoid the "coupling" with the article typography, since hero sections sometimes use larger fonts. I don't know how normal that is for designsystems though. Looking at gov.uk they have solved this by providing some helper classes for font-sizing: https://design-system.service.gov.uk/styles/typography/#font-override-classes.
> 
> Thanks for the feedback! We don't have an issue for it yet, but we have talked about providing more utility/helper classes just like [tailwind](https://tailwindcss.com/docs/font-size) and ukgov as you mentioned. Not just typography, but also things like borders, border-radius, spacing etc.
>
> There are also some problems using the font shorthand which we already plan to address #957 
> 
> We'll have a look again at what makes sense, best would be to find a solution that works now and for future needs also :)

**Comment by stianmorsund** [comment]
> We will arrange a meeting where we find a solution for this.

Nice 🎉  Let me know if you need more input from us :)
