### ISSUE TITLE
HelpText should have a portal property

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystemet#1358]
### Description of the bug

Portal support is missing on the `HelpText` component.

### Steps To Reproduce

1. Add a `HelpText` component to some web page
2. Observe that the component is not portaled to the root, and that there is no `portal` property to fix it

**Comment by mimarz** [comment]
Ah, thanks for reminding us! 

It was supposed to have one when we added on for Popover in #1287 in a separate PR but looks like we forgot it 🙈 

Sorry about that! We'll have it sorted soon :)
