### ISSUE TITLE
Add selection controls size tokens to Figma set

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1361]
With how browsers round css pixels and fluid sizing we get skewed circles. 

We have thus decided to add a separate token set using only `rem` values for sizing as they will not fluctuate as much due to viewport sizes. 

Suggest naming these sizing tokens something with selection controls, ref: https://m1.material.io/components/selection-controls.html#

Suggest token sizes using

| size | rem  | base@16px | 
|---|---|---|
| small | 1.5rem | 24px |
| medium | 1.75rem | 28px |
| large | 2rem | 32px |

**Comment by mimarz** [comment]
Decisions from #1444 might change this

**Comment by mrosvik** [comment]
This will be solved as part of #1444
