### ISSUE TITLE
Support large set of options for `Combobox`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1366]
Feature requested on our slack: https://designsystemet.slack.com/archives/C05RK9VEGJ0/p1704961095506939

There is a need to support almost 2000 options in the `Combobox`. 

This should be solved by using virtualisation methods, suggest we use [Tanstack Virtual ](https://tanstack.com/virtual/) for this.

Determine if we build-in support for this or make a story/example of using this library with `Combobox`.

**Comment by Barsnes** [comment]
Tanstack Virtual works fine when we only have single items that don't linebreak, and have the same height.
A problem occurs when we add a description or linebreak, and we get a variable height on all the options. We would need to first render the items, get their height, and then create a lookup list where we can reference it
