### ISSUE TITLE
Should accordion take 100% width on small screens?

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1368]
When testing the component in Figma we noticed that the accordion gets a lot of padding on small screens. We might want to document how they should behave or be used by our users. 

Inserted into a view with margins
![Skjermbilde 2024-01-11 kl  11 00 07](https://github.com/digdir/designsystemet/assets/33222679/51d905dc-b260-4122-bd83-05bcbe761574)

Examples where we ignore margins
![Skjermbilde 2024-01-11 kl  11 00 27](https://github.com/digdir/designsystemet/assets/33222679/76919aa0-f6fb-449b-a943-676600d70e21)

- [ ] Do we need to do something with our Figma components?
- [ ] Update guidelines (if we agree)
- [ ] What about the border variant. The border will go outside the view.

**Comment by eirikbacker** [comment]
Forslag; dette er noe som krever at vi vet hvor mye padding/luft som ligger rundt Accordion, og det vil kreve kontekstuell kunnskap som ikke er mulig uten videre i CSS. Det er lett å implementere for de som benytter vår accordion, men vanskelig for oss. Foreslår derfor at vi lukker denne? ☺️

**Comment by mimarz** [comment]
This will be solved by #2364
