### ISSUE TITLE
Design indeterminate state for `Checkbox`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1372]
[Figma](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=20759%3A80364&mode=design&t=FZEaC6DfmxCEsB1J-1)

- [x] Added indeterminate state for Checkbox
- [x] Did some changes to thickness of our checked mark

**Comment by Febakke** [comment]
Review done by @Edavda 
Closing this!
