### ISSUE TITLE
Add extra padding to chip component

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1385]
We have som feedback that the "x"- button are to close to the right edge. We should add a little extra padding so it seems more in balance with the padding on the left side.

One solution can be to add `spacing-2` too the right side of the component
![Skjermbilde 2024-01-15 kl  13 21 59](https://github.com/digdir/designsystemet/assets/33222679/91c44cdd-f79d-4f16-83ac-4d98b7392d49)

- [x] if we agree, fix in Figma
- [ ] Fix in react

**Comment by mimarz** [comment]
Make sure to test with "hover" on removable chip. This is from the react component today. More padding on the right might seem off maybe?

![Image](https://github.com/digdir/designsystemet/assets/1070981/0a9aa993-dedd-4bde-838d-938caf51332f)

**Comment by mrosvik** [comment]
Me and @Thuneer looked at this today. We have updated Chip in Figma with new colors, spacing and icon size: 

Old:

![Image](https://github.com/digdir/designsystemet/assets/1464915/d812d448-aa93-4950-b86d-e388b6c460ee)


New: 

![Image](https://github.com/digdir/designsystemet/assets/1464915/6ea6c1f7-46cb-4217-a8cb-4686b5c4bfa2)
