### ISSUE TITLE
Compact version of pagination is not compact enough for small screens

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1396]
When trying to use the pagination component on small screens its hard to scale it down to the correct size. You should be able to use a medium compact pagination on smaller screens.

![Skjermbilde 2024-01-17 kl  14 35 00](https://github.com/digdir/designsystemet/assets/33222679/f20da334-c990-4761-8d39-b20739dfac23)

- [ ] Add better scaling to the pagination component in Figma

**Comment by mrosvik** [comment]
When this picture was taken the viewport 320 was not active.
