### ISSUE TITLE
Pagination should have `<a>` semantics since it represents an act of navigation

### ISSUE THREAD

**Issue by tajakobsen** [digdir/designsystemet#1398]
### Description of the bug

The HTML of the Pagination-component uses `<button>` to represent each clickable page that the user can navigate to.

The general rule of semantics for buttons and links is that:
 1. `<a>` initiates navigation
 2. `<button>` initiates an action on the page

I suggest that the pagination component is changed to use `<a>` instead of (or in addition to) `<button>`. 

Note that if an `<a href="...">` the user should be able to interact with the link in every way they are used to, like opening it in a new tab.

### Steps To Reproduce

1. Open the Pagination page in Storybook
2. Inspect on a link and see that it is a `<button>`

### Additional Information

Image of the markup next to the preview of the component:

![pagination-semantics](https://github.com/digdir/designsystemet/assets/2621231/a8b6f145-e2ac-498c-aabd-f47ee620a060)

**Comment by Barsnes** [comment]
Thanks for the issue! :sparkles: 
As said on Slack, I agree. However, we have to make sure the user can choose what element is rendered, some might need `a`, `Button`, `NextLink`, etc.

I think we need to make some changes to the component API, to make sure this is possible.
Something like this is what I am thinking, but we would probably need to investigate a bit
```jsx
<Pagination>
  {/* with anchor */}
  <PaginationPrevious asChild>
    <a href="#">
      Forrige
    </a>
  </PaginationPrevious>

  <PaginationItem>
    <PaginationLink asChild>
      <a href="#">
        1
      </a>
    </PaginationLink>
  </PaginationItem>

  <PaginationEllipsis />

  {/* with button */}
  <PaginationItem>
    <PaginationLink href="#" isActive asChild>
      <button onClick={() => {}}>
        3
      </button>
    </PaginationLink>
  </PaginationItem>

  <PaginationNext asChild>
    <button href="#">
      Neste
    </button>
  </PaginationNext>
</Pagination>
```

**Comment by Barsnes** [comment]
Meeting 12.02:
Keep old `Pagination`, add new components `.Root`?, `.Item`, `.Next/Previous`, `.Ellipsis` etc.
Expose a new `usePagination` hook to aid in using pagination.

All components supports `asChild`, so users can change the rendered element.

```jsx
<Pagination.Root> // nav
  <Pagination.Content> // ul

    <Pagination.Item> // li
      <Pagination.Previous> // button
        Forrige
      </Pagination.Previous>
    </Pagination.Item>

    <Pagination.Item> // li
      <Pagination.Link> // button
        1
      </Pagination.Link>
    </Pagination.Item>

    <Pagination.Item> // li
      <Pagination.Ellipsis /> // p
    </Pagination.Item>

  </Pagination.Content>
</Pagination.Root>
```
