### ISSUE TITLE
`Link` is missing visited styling when inverted

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1405]
### Description of the bug

![image](https://github.com/digdir/designsystemet/assets/1070981/463c65cb-ffea-44ae-8502-1553d5f5dcdf)

### Steps To Reproduce

When I have clicked the link on inverted and go back, it does not have a styling which indicates it has been visited, while "normal" has. 

### Additional Information

Is this intended? I see it has not styling for visited in Figma...

- [Figma link](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=12585-103339&mode=design) 
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/1623
- [ ] Implement visited inverted link color in react
```

**Comment by mrosvik** [comment]
A light purple color?

**Comment by Barsnes** [comment]
We no longer have `inverted` link, and when chaning to dark mode it is now purple: 
![image](https://github.com/user-attachments/assets/b2eb294a-52ce-404a-ae1e-bfae522cbb8a)

**Comment by Febakke** [comment]
This is solved in Figma and code 🥳
