### ISSUE TITLE
Add "danger" icon to the error summary

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1411]
We should concider adding the "danger" icon to our error-summary.

- [ ] Are there any negative effects of using one of the alert icons in this scenario?
- [ ] If we decide on adding an icon: Fix this in Figma

**Comment by Barsnes** [comment]
If we add the icon, would it not be 99% identical to `Alert`? If so, I don't see a reason to create a separate for `ErrorSummary`. I think it would be better to create an example of how you construct an `ErrorSummary` from the `Alert` component.

They already look pretty similar:
<img width="503" alt="image" src="https://github.com/digdir/designsystemet/assets/14057205/671289d1-094d-4b7c-923b-cc1c8c33da3d">
<img width="696" alt="image" src="https://github.com/digdir/designsystemet/assets/14057205/f4896174-2380-4fbd-8fb6-aa64c7d9053d">
