### ISSUE TITLE
Add default meta images on storefront

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#1420]
Currently our pages don't have a meta image tag, this is used to display images when sharing links on ex. Slack.

What it looks like now:
![image](https://github.com/digdir/designsystemet/assets/14057205/6a31905c-f1e9-41ef-bdc5-5520ad4b45eb)

What it could look like:
![image](https://github.com/digdir/designsystemet/assets/14057205/42c64419-1e25-499e-9735-41b8be5501c8)

We need to investigate how we can add a default image, and if we can use our `Meta` component to set custom images for pages.
We can use this website to check what it looks like: [https://metatags.io/](https://metatags.io/)

**Comment by mrosvik** [comment]
@Barsnes @Thuneer Funker denne i første omgang?

![Image](https://github.com/digdir/designsystemet/assets/1464915/6e5333aa-9c5b-4e1b-80ea-86a79f726a64)

**Comment by Barsnes** [comment]
Synst det ser bra ut 😄 Kan alltids endre på seinare

**Comment by Thuneer** [comment]
Ser fin ut!
