### ISSUE TITLE
Textarea - bug in Figma with counter and focus

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1446]
The focus outlines should stick to the textarea, when using counter. 

![Image](https://github.com/digdir/designsystemet/assets/1464915/9e30b6e3-e855-4a7b-9744-acda7a4eb8b0)

**Comment by Febakke** [comment]
We have decided to remove focus variants on our components as this is not essential to use in Figma prototypes. Because of this, the issue will not be a problem anymore.
