### ISSUE TITLE
Spacing in button is weird

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1449]
When having an icon inside the button, the left spacing is larger than the spacing between the icon and the text.

**Comment by Febakke** [comment]
This might do the trick in Figma: https://forum.figma.com/t/adjusting-for-optical-balance-when-using-layer-properties-for-button-icons/35399

**Comment by mrosvik** [comment]
This is fixed in the Figma branch "static" that comes with new sizing and spacing props.
