### ISSUE TITLE
Controlled `ToggleGroup` sets focus to old item

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#1473]
### Description of the bug

If we have a controlled `ToggleGroup`, it will always select the wrong item when tabbing to it, if the state has changed.

If we have `1`, `2`, `3` as items, and we have selected `3`, it will set focus to that item when tabbing to the `ToggleGroup`.

However, if we update the current value to be `2`, it will still set focus to item `3`.

### Steps To Reproduce

Use the controlled example in storybook: [https://storybook.designsystemet.no/?path=/story/felles-togglegroup--controlled](https://storybook.designsystemet.no/?path=/story/felles-togglegroup--controlled)

**Comment by mrosvik** [comment]
Is this still relevant? @Barsnes

**Comment by Barsnes** [comment]
> Is this still relevant? @Barsnes

yes this should still be an issue, afaik

**Comment by Barsnes** [comment]
This is an issue in `RovingTabIndex`, and will affect all components using this.
Will look into fixing this before we expose it in #2130

**Comment by eirikbacker** [comment]
Good opportunity to test https://u-elements.github.io/u-elements/elements/u-tabs? ☺️

**Comment by Barsnes** [comment]
This should have been fixed in https://github.com/digdir/designsystemet/pull/2130/commits/8a287f82623cacf84f65f9df1388f1dfc38e8bfb

**Comment by Barsnes** [comment]
Resolved in #2130
