### ISSUE TITLE
Link: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1484]

**Comment by Ildest** [comment]
Ann-Elisabeth tar denne

**Comment by Ildest** [comment]
Lagt til Word-fil i Teams

**Comment by Ildest** [comment]
Draft submitted by Ann-Elisabeth in https://digdir.sharepoint.com/:w:/r/sites/bod-bbo/Delte%20dokumenter/Team%20Designsystem/God%20praksis%20og%20retningslinjer/Komponenter/Link.docx?d=w1782570060ac46269ccbb6ed6e5f58b1&csf=1&web=1&e=grwiH0
