### ISSUE TITLE
Loader: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1487]

**Comment by Ildest** [comment]
Lagt til Word-fil i Teams

**Comment by Ildest** [comment]
Status 21. March:  Draft submitted by Ann-Elisabeth: https://digdir.sharepoint.com/:w:/r/sites/bod-bbo/Delte%20dokumenter/Team%20Designsystem/God%20praksis%20og%20retningslinjer/Komponenter/Loader.docx?d=wb39d63b54b6f4ee9adc264b337010f7a&csf=1&web=1&e=ciXc5b
