### ISSUE TITLE
TextArea: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1492]

**Comment by Ildest** [comment]
Lagt til Word-fil i Teams

**Comment by Ildest** [comment]
Word file delivered in https://digdir.sharepoint.com/:w:/r/sites/bod-bbo/Delte%20dokumenter/Team%20Designsystem/God%20praksis%20og%20retningslinjer/Komponenter/Text%20area.docx?d=w9ea0b055a40c489eb5c6fa578324b5a8&csf=1&web=1&e=Y0gWSk

**Comment by Ildest** [comment]
Ready for Storybook after @Febakke  and I reviewed it today.
