### ISSUE TITLE
Tooltip: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1494]

**Comment by Ildest** [comment]
Lagt til Word-fil i Teams

**Comment by Ildest** [comment]
Status 21. March: In progress by Ann-Elisabeth

**Comment by Barsnes** [comment]
We need to add a story about how to use this in a `Modal`.
Ad outlined in #2053, the `Tooltip` needs `portal={false}` to be set.
