### ISSUE TITLE
Table: Type-errors when using native table properties

### ISSUE THREAD

**Issue by Magnusrm** [digdir/designsystemet#1499]
### Description of the bug

Typescript is complaining when using properties such as `colSpan` or other properties for the TableCell component ([HTMLTableCellElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement)).
The properties work as expected when set, but typescript is complaining.

`React.HTMLAttributes<HTMLTableCellElement>`  should be `React.TdHTMLAttributes<HTMLTableCellElement>`

The same issue also exists for the other table subcomponents.

![image](https://github.com/digdir/designsystemet/assets/32294735/06d6bdc9-a413-43c6-a402-50ab33eb9cac)

### Steps To Reproduce

Use 'colSpan' in Table.Cell component and run Typescript typechecking.

**Comment by mimarz** [comment]
Thanks for reporting 🙏 

This is a simple fix, we'll get it sort for our next release next week 😁
