### ISSUE TITLE
Add a property for specifying a background color on the header of a Table component 

### ISSUE THREAD

**Issue by mikaelrss** [digdir/designsystemet#1515]
### Description

Altinn is currently refactoring away from the `LegacyTableComponent` to the new `Table` component. The new components have some visual changes, and we would like some options to customise the visual style.

We want to be able to set a background color on the new `Table` header. We think we might benefit from this being a configurable option in the design system, as this will allow us to select/use a background color that is in line with the design goals of the design system.

**Comment by mimarz** [comment]
Thanks for requesting this feature! 

Do you have any examples of what kind of background colors for the `Table`? 

I know we have some surface colors (default and subtle), but not maybe for this specific use-case?

I think the idea was for people to just use `className` and define their wanted `background-color` if needed. 

Do you have any thoughts on this @Febakke @mrosvik ?

**Comment by mikaelrss** [comment]
Here are some examples of diffs. Today we only use one color (I think), and it is a `#f5f5f5` (which does not exist in the design system at all)
![image](https://github.com/digdir/designsystemet/assets/26043795/114c39e8-0ebe-4555-93a1-a4ca1f49d81d)
![image](https://github.com/digdir/designsystemet/assets/26043795/a1e22c5b-eb34-4f88-a93c-d2edbce4c95c)

And we have already used `className` to define the background color where we felt it was absolutely necessary: 
![image](https://github.com/digdir/designsystemet/assets/26043795/2577c30f-e170-493a-9c12-031f092efc70)
![image](https://github.com/digdir/designsystemet/assets/26043795/7b3416b0-a632-44ee-9cdd-cddd43e65c0e)

Likert component:
![image](https://github.com/digdir/designsystemet/assets/26043795/dfb7edc2-8479-495a-ac5d-58440b8e129e)
![image](https://github.com/digdir/designsystemet/assets/26043795/b80d227f-728a-43f1-9496-5617ff1e7af4)

If specifying custom styles is the intended way to do this, we will just use `className` :muscle:

**Comment by mimarz** [comment]
Thats a lot of different styled tables 😅 Why not have the same style for all of them? 
I would think we would want to get a more uniform experience when it come to tables? 

Here are some examples for the new design using table: https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Designsystemet---Core-UI-Kit?type=design&node-id=24906-2056&mode=design

Maybe having a background-color on header/cell is intended to use for interaction on stuff like sorting, but I am not sure what the thought is here 🤔 


As for background color, I guess the closes on would be subtle background (`--fds-semantic-background-subtle`)
![image](https://github.com/digdir/designsystemet/assets/1070981/b8d83a3b-4921-45de-9cd9-49fc6e8c9b49)

**Comment by Febakke** [comment]
@Edavda and Olav from Team Apps should have a look at this

**Comment by mikaelrss** [comment]
I should have specified that the screenshots include the `LegacyTable` version and the new `Table` version :sweat_smile: 

I am not sure why there exist so many different table styles, but I guess they have appeared over time as needs grow. App owners are able to compose tables within tables in the `RepeatingGroup` component, which I guess gives a need to make the nested table (the middle example) appear a bit different visually. 

The two colors you suggested are the two colors I have used as of now in the middle example :raised_hands:

**Comment by Barsnes** [comment]
I have added the css vars in the next branch, you can see how it will work here: https://github.com/digdir/designsystemet/blob/next/packages/css/table.css

**Comment by Barsnes** [comment]
Hi, are we able to close this issue?
In the next branch you can change the background using tjis css var: `--dsc-table-header-cell-background`

**Comment by mikaelrss** [comment]
With being able to style the table header with a css var, this solves our original need, so I think this issue can be closed yeah :raised_hands:
