### ISSUE TITLE
The more options, the longer time it takes to open the Combobox dropdown

### ISSUE THREAD

**Issue by hansenalexander** [digdir/designsystemet#1516]
### Description of the bug

Title basically, this starts to be slightly noticeable at around 365 elements, and is very noticeable at around 1800 elements.

I've created an example here: https://codesandbox.io/p/devbox/autumn-platform-j8z3wh

### Steps To Reproduce

Add ~365 or more options to a Combobox.
Open the combobox.

**Comment by mimarz** [comment]
Just a headsup we haven't forgotten this :) 

We did some quick testing to see if could improve this without avail, so this is a bigger deep-dive/investigation thats needed.
