### ISSUE TITLE
Storefront: Header adjustments

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#1526]
Some small adjustments to the menu item border and spacing.

```[tasklist]
### Tasks
- [x] Finish design of changes
- [x] Develop Header changes
```

Figma: https://www.figma.com/file/hpNSt9jMeVTH46Fh9TENBE/Storefront?type=design&node-id=1674%3A662&mode=design&t=f8iTQq3zdq6K8Fv4-1

**Comment by Barsnes** [comment]
@Thuneer Should this be closed?

**Comment by Thuneer** [comment]
Good catch! I will close this.
