### ISSUE TITLE
Design "Add new value" for the combobox component

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1533]
Design added to our Figma component. [Link](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Designsystemet---Core-UI-Kit?type=design&node-id=23308%3A75707&mode=design&t=uayMLMLqYURl31kA-1)

Examples:
![Image](https://github.com/digdir/designsystemet/assets/33222679/ffcda989-e993-47ca-90dc-330bddbabad9)

Hover/fokus on sub-component (With comparison to normal value)
![Image](https://github.com/digdir/designsystemet/assets/33222679/fc1f857c-07e1-4920-932e-0428739c9da1)

- [ ] Should it be placed over or under "fant ingen treff på søket" 
- [ ] How should it behave when the user has selected something and search a value that is not in the list?

**Comment by mrosvik** [comment]
![Image](https://github.com/digdir/designsystemet/assets/1464915/b4e781c8-c323-410d-ab32-774b42ad5b27)

2px instead of 3?

**Comment by Febakke** [comment]
> ![Image](https://private-user-images.githubusercontent.com/1464915/309696899-b4e781c8-c323-410d-ab32-774b42ad5b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDY5MzEsIm5iZiI6MTcwOTkwNjYzMSwicGF0aCI6Ii8xNDY0OTE1LzMwOTY5Njg5OS1iNGU3ODFjOC1jMzIzLTQxMGQtYWIzMi03NzRiNDJhZDViMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTQwMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJkOTYyMGZjYTYxYmIxZDQ1ZmI3ZWI2Mjk5YWU0YjBkOTFmOGM4MTYzMGNhN2NlYzI1NTA5ODQzMTNlNGE1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-hJmQOQlKR4ABDC6ZYag_1ZRBZ-QVvarlOrV83EuAmc)
> 
> 2px instead of 3?

Fixed 👍

**Comment by Febakke** [comment]
This needs to be looked at again and implemented in `Suggestion`
