### ISSUE TITLE
Forward ref to Combobox component

### ISSUE THREAD

**Issue by Chlenix** [digdir/designsystemet#1546]
### Description of the bug

`Combobox` should be able to forward ref

### Steps To Reproduce

Does not accept `ref`

**Comment by mimarz** [comment]
Thanks for reporting this! 

I think we might just have missed this as there are quite a lot of parts in Combobox. I assume you are interested in the `ref` on the `input` thats used inside `Combobox`?

**Comment by Chlenix** [comment]
Yes, `ref` on the `input`
