### ISSUE TITLE
Scaling UI icons doesn't look right (NAV Aksel icons)

### ISSUE THREAD

**Issue by marlinhjallum** [digdir/designsystemet#1573]
### Description of the bug

Hei! Jeg forsøker å dra nytte av UI ikonene fra NAV Aksel som dere foreslår, og har kopiert dem fra Figma Community/plugin, men får problemer med uttrykket når jeg skalerer ikonene i mindre størrelser i Figma.  Dersom man skalerer ned ikonene via frame properties i høyremenyen, så blir streken veldig chunky og utydelig (noe jeg mistenker er fordi ikonene ikke er outlined shapes, men stroke, så tykkelsen på streken skalerer ikke i takt med størrelsen man setter ikonet til), i tillegg til at en del ikoner også mister formen sin siden de ulike lagene innad i ikonet ikke er ett vektorlag.

Det er litt problematisk fordi man bør kunne bruke ikoner i andre størrelser enn default (24px) for at det fks skal kunne brukes i inputfelter, validering osv.

Det blir litt bedre skalering på strektykkelsen når man bruker en alternativ måte å stille inn høyde og størrelse i Figma på, ved å bruke “scale” funksjonen (shortcut K), fremfor å skrive inn i selve frame-properties, men likevel ikke helt som ønsket oppførsel.

<img width="653" alt="Screenshot 2024-02-26 at 09 49 49" src="https://github.com/digdir/designsystemet/assets/31203990/cf1281a2-56a3-4169-a05c-06fa19ef2c02">
<img width="638" alt="Screenshot 2024-02-26 at 09 49 38" src="https://github.com/digdir/designsystemet/assets/31203990/9c9338aa-4f02-4583-bd34-e2812271731a">

### Steps To Reproduce

1. Insert icon asset from NAV Aksel in Figma 
2. Scale properties down to 12px, 16px etc

```[tasklist]
### Tasks
- [x] Test if we can use the swap libraries to get the new icons without breaking any connections
- [ ] Are we missing any icons that needs to be included?
```

**Comment by Febakke** [comment]
Hei! @marlinhjallum Beklager sent svar her!
Dette er slik ikonene er laget fra Aksel nå. De har outline stroke på `filled` variantene om jeg husker rett, men ikke på `stroke`. 

Vi har oppdaget dette selv og har brukt scale som en workaround. Det funker i noen tilfeller, men ikke i alle dessverre. Det er også utfordringer med å swappe og bytte varianter. 
Dette er kun et problem i Figma og heldigvis ikke i koden. En fordel med dette er at man endre stroke-width som kan være ønskelig for å få de til å passe den konteksten de er i. 

Jeg håper scale fungerer godt nok for bruken din, hvis ikke får vi melde det inn til Aksel og høre hva de tenker.

**Comment by mimarz** [comment]
Closing this as we have not gotten any response. 

https://altinndevops.slack.com/archives/C048MUWHJ9E/p1709295418739319

**Comment by sjur-gr** [comment]
Vi endret ikonene fra Aksel til shapes for litt siden. Om dere henter ned community-fila på nytt så skal det funke.

**Comment by Febakke** [comment]
Da er det vi som ikke har fulgt med. Vi oppdaterer filen nå 😄
