### ISSUE TITLE
Create test-file for Figma 

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1601]
We have no way of testing if we break anything when we publish a new version of our component library. If we create a testfile with all components and overwrite texts and other elements designers are ment to overwrite. Then we can quickly check that we dont break anything we dont intend to break when publishing. 

- [ ] All components are present
- [ ] Its easy to see that a text-overwritten and states are kept as-is

**Comment by mrosvik** [comment]
Test-file: https://www.figma.com/design/5x3i5T512RVrbUDn8PW4H6/Eksempler?node-id=2-16245&t=JekhpSuEGrp5UozP-1
