### ISSUE TITLE
Tooglegroup kb navigation does not work without defined values on children

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1612]
### Description of the bug

The component works as normal with mouse clicks but does not work with arrow keys or correct tab-focus if `value` is not defined on 

### Steps To Reproduce

- Use keyboard navigation and tab until `ToggleGroup` is in focus
- Try to use arrow keys to navigate to left/right items
- Focus jumps immediately to last item.

### Additional Information

Might related to #1473

**Comment by Barsnes** [comment]
This is solved in #2130 by generating a random value if it is not set, using `useId()`
