### ISSUE TITLE
Update title and meta description for search engine results page

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1613]
![Image](https://github.com/digdir/designsystemet/assets/1464915/60933400-9251-49ff-9c79-45626312109e)

Change to: 

Designsystemet
Her finner du UI-komponenter, retningslinjer og god praksis for effektiv produktutvikling og helhetlige brukeropplevelser.

**Comment by Barsnes** [comment]
A lot of our pages are missing a meta descriptions as well, most of them have "Beskrivelse". 
Should I update these as well?
