### ISSUE TITLE
`Combobox` input sometimes does not have `Inter`-font 

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#1632]
Recieved multiple reports of this in Slack.

It looks like the `font-family: Inter` is not being set correctly on the input of the `Combobox`. From the screenshot, it looks like `Times New Roman` is being used. Chips have been reported to work fine, so we need some investigation into why this is not working.

Some of our components are using `font-family: inherit`, which might be a solution to this problem.

It has also been reported that using other fonts also recieves the same bug, recieved this image on Slack, which does not use `Inter`:
![image](https://github.com/digdir/designsystemet/assets/14057205/9665db90-8012-43bf-bed4-9e3afb55911a)

**Comment by bjosttveit** [comment]
In this example, the `Inter` font is not loaded into the app at all, so I suppose this could be expected.
![bilde](https://github.com/digdir/designsystemet/assets/47412359/62634cc3-2491-446e-a364-8a49d7ae784a)

**Comment by Barsnes** [comment]
> In this example, the `Inter` font is not loaded into the app at all, so I suppose this could be expected.
> 
> ![bilde](https://private-user-images.githubusercontent.com/47412359/309768137-62634cc3-2491-446e-a364-8a49d7ae784a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTkyODMsIm5iZiI6MTcwOTU1ODk4MywicGF0aCI6Ii80NzQxMjM1OS8zMDk3NjgxMzctNjI2MzRjYzMtMjQ5MS00NDZlLWEzNjQtOGE0OWQ3YWU3ODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEzMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YTQyOTdkNTQwNTlkNmU1NTEyOWE3MTc2MmUwMzY4Zjc5NjQ5NzJhMzlmZDEzMDM5YWE2ZDE0YzBiYmFmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.efhGiDHZGt735SNxzAOLlTMnu989dloB2SdPmOKZ8jI)

Thanks for correcting me, updated the issue 🚀

**Comment by mimarz** [comment]
This is why we love our community! <3 

We can fix this for now by adding `font-family: inherit` after [font](https://developer.mozilla.org/en-US/docs/Web/CSS/font) where we have used that shorthand. We should fix this for all occurrences where its missing. 

For example in Combobox [here](https://github.com/digdir/designsystemet/blob/8f3ec713a01c71b1a783e830469a219dba9c44cf/packages/react/src/components/form/Combobox/Combobox.module.css#L40) 

We have planned to find a better solution for this in the future but for now this should suffice :)

**Comment by Barsnes** [comment]
This might be resolved in #1638, but keeping this issue open until we can verify

**Comment by Barsnes** [comment]
@bjosttveit We published version [0.51.3-alpha.0](https://www.npmjs.com/package/@digdir/design-system-react/v/0.51.3-alpha.0). Can you check if this resolves the issue?

**Comment by bjosttveit** [comment]
> Can you check if this resolves the issue?
@Magnusrm check it out when you have some spare time 😄

**Comment by Magnusrm** [comment]
@bjosttveit Will do! 👍

**Comment by Barsnes** [comment]
I tested this in another application that was experiencing the same issue, and with the prerelease we published it was resolved.

**Comment by mimarz** [comment]
This should be fixed now, can you confirm? @Magnusrm @bjosttveit

**Comment by bjosttveit** [comment]
Confirmed ✅ 

<img width="637" alt="bilde" src="https://github.com/digdir/designsystemet/assets/47412359/f0450163-f040-4847-a904-1e852892a384">

**Comment by mimarz** [comment]
Marking as solved :)
