### ISSUE TITLE
`Combobox`: Triggering `onChangeValue` on Render

### ISSUE THREAD

**Issue by lassopicasso** [digdir/designsystemet#1640]
### Description of the bug

I encountered unexpected behavior while working with the `combobox` component. The `onChangeValue` property seems to be triggered during the rendering phase,

CodeSandbox example:
https://codesandbox.io/p/sandbox/react-typescript-forked-ms4mgx?file=%2Fsrc%2FCombobox.tsx

### Steps To Reproduce

The same example as in the codesandbox

```
export const ComboboxExample = () => {
  const selectedValues = ["test1"];
  const values = ["test1", "test2"];

  const handleComboboxChange = (value: string[]) => {
    console.log("test", value);
  };

  return (
    <Combobox
      id={"attachmentList"}
      multiple
      value={selectedValues}
      onValueChange={handleComboboxChange}
    >
      {values.map((attachment) => {
        return (
          <Combobox.Option
            value={attachment}
            description={attachment}
            displayValue={attachment}
          />
        );
      })}
    </Combobox>
  );
};
```

**Comment by Barsnes** [comment]
Hi, the initial value is an empty array `[]`, so if you send in a different `value` it is expected that `onValueChange` is called.
Not sure if this is a bug 🤔 
@mimarz thoughts?

**Comment by mimarz** [comment]
> Hi, the internal initial value is an empty array `[]`, so if you send in a different `value` it is expected that `onValueChange` is called. Not sure if this is a bug 🤔 [@mimarz](https://github.com/mimarz) thoughts?

This use-case relates to having pre-selected values on initial render. We'll have a look at how we can best solve this.

**Comment by mimarz** [comment]
This should be solved by this [1698](https://github.com/digdir/designsystemet/issues/1698)

**Comment by lassopicasso** [comment]
Thanks :)

**Comment by Barsnes** [comment]
@lassopicasso Have you checked if the issue has been resolved? If so, we'll close this issue 😄

**Comment by lassopicasso** [comment]
Hm.. it can seem like the `onChangeValue` property continues to be triggered during the rendering phase.
I've tested in this example: 
https://codesandbox.io/p/sandbox/react-typescript-forked-ms4mgx?file=%2Fsrc%2FCombobox.tsx%3A33%2C1

**Comment by Barsnes** [comment]
> Hm.. it can seem like the `onChangeValue` property continues to be triggered during the rendering phase. I've tested in this example: https://codesandbox.io/p/sandbox/react-typescript-forked-ms4mgx?file=%2Fsrc%2FCombobox.tsx%3A33%2C1

Looks like this example is not using the new `initialValue` prop, which is what we decided to add - instead of changing how the `value` prop behaves

**Comment by lassopicasso** [comment]
My bad, tested it with the new prop now. Seems to work like a charm in the sandbox. Well done!
