### ISSUE TITLE
Spinner component is missing colors

### ISSUE THREAD

**Issue by PieNappl3** [digdir/designsystemet#1647]
### Description of the bug

the default and inverted spinner uses --color-grey-200 and --color-grey-500 but i cant find these colors after adding the dependencies @digdir/design-system-react and @digdir/design-system-tokens i only found --fds-colors-grey-200 in tokens and --fds-semantic-border-action-first-default found in variant "interaction" 

### Steps To Reproduce

install dependencies @digdir/design-system-react and @digdir/design-system-tokens
add imports 
add ```<Spinner size="large" title="title" variant="default"/>```  to page

**Comment by mimarz** [comment]
Doh! 

Can confirm this is a bug 🐛 

The css variables you mention are part of the old token package (`@altinn/figma-design-tokens`) which we don't use anymore, so unfortunately something we missed transitioning away 🙈

**Comment by mimarz** [comment]
We are currently working on a fix for this and also adjusting the colors for better legibility.

Should get a fix released soon :)
