### ISSUE TITLE
Contributors in blog article should work on multiple lines

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1648]
Det bør være mulig å ha flere linjer med bidragsytere. 

![Image](https://github.com/digdir/designsystemet/assets/1464915/1d71c2e3-8db0-4bc3-8119-a6d4fa1fda93)

- Den første injen har en rød dott i slutten
- Mer spacing under Bidragsytere

Kanskje slik?

![Image](https://github.com/digdir/designsystemet/assets/1464915/3ea3ffbb-0f2a-426b-855a-388aef9a1205)

Vi må også passe på at når det er få navn på siste linje at de ikke blir spredd:

![Image](https://github.com/digdir/designsystemet/assets/1464915/bc18cfb7-5f30-45c4-954a-a94724e14bbd)

**Comment by mrosvik** [comment]
@Thuneer might have inputs on this..

**Comment by Thuneer** [comment]
I agree on a little more spacing between the title and the content, but not too much spacing. Should be more spacing around the box (padding), and a bit less between the title and content. This makes the title and content look like one unit. Spreading the names to fit the container width works for some combinations, but looks a bit weird if there are only 2 names. I would not spread personally, so the names look more together, like this: 

![image](https://github.com/digdir/designsystemet/assets/13560642/34713dfb-ae24-4839-8e96-6d098c5896d8)

**Comment by mrosvik** [comment]
Totally agree! 🙌
