### ISSUE TITLE
Tertiary button not aligning with our other components

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1654]
When aligning elements in Figma you get a weird extra padding with tertiary button as the clickarea is a part of the button. We look into if we can change the framing of the component so that it behaves as expected. The tricky part will be to make it work with hover without making it bounce back and forth 🤔

### Proposed solution
Create guidelines for both Figma and Code on how to correctly align theese components

<img width="697" alt="Skjermbilde 2024-03-08 kl  10 42 59" src="https://github.com/digdir/designsystemet/assets/33222679/bc2ea6ff-694e-4814-815c-2feaa3beff15">

```[tasklist]
### Tasks
- [ ] Fix in figma / We should concider making a guide instead
- [ ] Write guidelines
```

**Comment by mrosvik** [comment]
I think it is correct the way it is now. The hover will be aligned to the other content.

**Comment by mimarz** [comment]
We can't solve this in our components as its very dependant on context, in addition it will make focus/hover bleed on the outside. 

If users want to align this with input fields, we suggest they solve it themselves with use of for examples minus-margins in CSS.
