### ISSUE TITLE
Radio and checkbox not properly left aligned in code

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#1655]
Radio and Checkbox are not aligned properly because of the hover effect that is outside of the visual bounding box.
Suggest adding a minus margin on both. This is done in Figma.
Codesandbox: https://codesandbox.io/p/sandbox/objective-heyrovsky-vty4pj?file=%2Fsrc%2Findex.js

**Comment by mimarz** [comment]
Blocked by #1735

**Comment by mimarz** [comment]
This will be solved by #1735
