### ISSUE TITLE
Accordion: Refresh causes Server Error ReferenceError: window is not defined

### ISSUE THREAD

**Issue by maritAndreassen** [digdir/designsystemet#1665]
### Description of the bug

I am using the accordion component in our application. When I refresh the page where I use this component it gives me a server error. Looks like window is not handled correctly.
![MicrosoftTeams-image](https://github.com/digdir/designsystemet/assets/44979682/d40c0219-3c99-49e3-ae11-cda9cef5f538)

### Steps To Reproduce

1. I start up my application locally.
2. Navigate to my page where I use the accordion component
3. Refresh the page and the error occurs.

**Comment by mimarz** [comment]
Thanks for reporting this! 

We'll have a look and see if we can't fix this :)

**Comment by Barsnes** [comment]
Hi, this issue was sent in when we did not have tree shaking.
Can you try upgrading to the new package `@digdir/designsystemet-react`, and see if this happens?

Since every component is in the `index.js` file, it might be fixed in the new package that uses tree-shaking.

Here is our migration guide: https://github.com/digdir/designsystemet/blob/main/MIGRATION.md

**Comment by maritAndreassen** [comment]
I am still getting the same error. Now I am on v0.54.0

**Comment by Barsnes** [comment]
I tried this on Codesandbox with NextJS app router - and everything seems to work fine here.
Are you using sub components? 
Here is a link to the sandbox: https://codesandbox.io/p/devbox/fds-accordion-p5mfz7

If you are, could you perhaps try to do 
```tsx
      <Accordion>
        <AccordionItem>
          <AccordionHeader>Accordion header text</AccordionHeader>
          <AccordionContent>Accordion content</AccordionContent>
        </AccordionItem>
      </Accordion>
```
instead of 
```tsx
      <Accordion>
        <Accordion.Item>
          <Accordion.Header>Accordion header text</Accordion.Header>
          <Accordion.Content>Accordion content</Accordion.Content>
        </Accordion.Item>
      </Accordion>
```

**Comment by Barsnes** [comment]
Hi @maritAndreassen did the solution above work for you? 
When in a server component, we can't access sub-components on client components - and that is why we are also exporting all components separately.

Let me know if you are still experiencing an error, or we'll close the issue 😄

**Comment by maritAndreassen** [comment]
I still get the same error, even after trying your suggestion.

**Comment by maritAndreassen** [comment]
It did not work either, but I tried to set up an example in Codesandbox like you did and I got the same error. I checked your example and I saw the same error in the top of the console/terminal:
`⨯ Internal error: ReferenceError: window is not defined
    at getMatches (./node_modules/.pnpm/@digdir+designsystemet-react@0.54.0_@types+react@18.2.48_react-dom@18.2.0_react@18.2.0/node_modules/@digdir/designsystemet-react/dist/esm/hooks/useMediaQuery.js:9:70)
    at useMediaQuery (./node_modules/.pnpm/@digdir+designsystemet-react@0.54.0_@types+react@18.2.48_react-dom@18.2.0_react@18.2.0/node_modules/@digdir/designsystemet-react/dist/esm/hooks/useMediaQuery.js:10:83)
    at AnimateHeight (./node_modules/.pnpm/@digdir+designsystemet-react@0.54.0_@types+react@18.2.48_react-dom@18.2.0_react@18.2.0/node_modules/@digdir/designsystemet-react/dist/esm/utilities/AnimateHeight/AnimateHeight.js:28:98)`

**Comment by Barsnes** [comment]
> I still get the same error, even after trying your suggestion. I can try to make a client component with the code where I use the Accordion component, and see if it works.

Alright, it seems like we managed to recreate the same issue in #1362, where we are using NextJS with the pages router.
It should not complain, since all our components are marked with `'use client'`. 

I'll do some investigation and get back to you as soon as possible!

**Comment by Barsnes** [comment]
> Btw, if I remove AccordionContent the error disappears.

The error comes from our `AnimateHeight` component, which we use internally, which then uses `useMediaQuery`.
This is the hook that gives the error, since it is using `window`. The hook only returns a boolean, so we should be able to return `false` if `window` is not defined.

I will have to look into if this will have any side-effects

**Comment by Barsnes** [comment]
@maritAndreassen We published a potential fix under the `next` tag on npm, could you try and see if that fixes it for you?

```
 - @digdir/designsystemet-css => 0.3.3-alpha.2
 - @digdir/designsystemet-react => 0.56.3-alpha.1
 - @digdir/design-system-react => 0.53.7-alpha.2
 - @digdir/designsystemet-theme => 0.15.1-alpha.3
```

I tested it in my sandbox from earlier, and there is not error in the console anymore: https://codesandbox.io/p/devbox/fds-accordion-p5mfz7

**Comment by maritAndreassen** [comment]
Sorry for the late response. This fix solved my problem. :smiley:  Thank you!
