### ISSUE TITLE
New component: Badge

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1694]
Component requested by Dialogporten.

The need is for a component to indicate a number of notifications using numerical values that can be attached or inlined with other elements.

Things to consider:
- Need to review this against usage with `Tag`
- Is this just `Tag` with rounded borders or a separate component? Mixed definitions out here

Examples
- https://atlassian.design/components/badge/examples
- https://orbit.kiwi/components/information/notificationbadge/

**Comment by mimarz** [comment]
If we get the time we could look at this before v1, or else after.

Should be done in conjunction with #1092

**Comment by Barsnes** [comment]
Tag vs Badge: 
> Badges and tags are visually similar, but tags are interactive and badges are not. 
ref: https://www.delldesignsystem.com/components/badge/
