### ISSUE TITLE
Combobox: Add a prop to hide the "Clear selection" button

### ISSUE THREAD

**Issue by hansenalexander** [digdir/designsystemet#1701]
### Description

When separating the combobox and the selected values (chips) I think it makes sense to have the ability to toggle off/hide the "Clear selection" button. It's not quite clear what the button does just by looking at it, some may think it's a button to remove the text.

In addition to this it would be nice to have better control of the button, so one could change the what the button does, but this isn't a part of this feature request.

**Comment by mimarz** [comment]
We'll add this feature soon!
