### ISSUE TITLE
Combobox: When filtering, selected values is always shown

### ISSUE THREAD

**Issue by hansenalexander** [digdir/designsystemet#1722]
### Description of the bug

Not sure if this is a bug or intentional, but shouldn't filtering only show the actual matches regardless of whether the value is selected or not? 

![Screenshot from 2024-03-20 22-52-25](https://github.com/digdir/designsystemet/assets/75268558/b6ff4382-2664-42aa-ba01-58963a653028) 
Screenshot from the [docs](https://storybook.designsystemet.no/?path=/docs/komponenter-combobox--docs#multiple).

### Steps To Reproduce

1. Go to [docs](https://storybook.designsystemet.no/?path=/docs/komponenter-combobox--docs#multiple)
2. Select a couple values
3. Try to filter for something you haven't selected

**Comment by Barsnes** [comment]
This was changed a few releases back to always show. It is to help people with screenreaders be able to always deselect their options, since they might not know that they can tab back to remove them - so yes, this is intentional 😄

**Comment by mimarz** [comment]
This was done due to feedback of use with screenreaders, detailed in #1519
