### ISSUE TITLE
Should spacing and sizing be combined to only one scale?

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1724]
Several design systems have chosen to only go for one scale for `Sizing` and `Spacing` as these are the same values anyway. We should consider to do the same, to avoid two scales with the same values that could be confusing.

**Comment by mrosvik** [comment]
Til info!
Pga Token Studio så må vi fortsatt bruke sizing tokens. Hvis ikke kan vi ikke sette høyder på elementer. Litt irriterende at de har delt det inn på den måten, Figma har ikke noen sånne begrensninger med deres variabler og vi er redd mange kommer til å bli forvirret når du skal bruke hvilke. I Token Studio har du ikke noe valg, du bruker riktig uansett.

Du kan altså ikke sette en spacing til å være Width eller height:

![Image](https://github.com/digdir/designsystemet/assets/1464915/cf942ab5-fb30-4875-b677-4e5fc3eaaa21)

Og du kan ikke sette en sizing til å være top, left, right, bottom:

![Image](https://github.com/digdir/designsystemet/assets/1464915/597607e7-0c0e-4340-952c-b0f58fe236de)

Var derfor vi endte opp med å ha både sizing og spacing som to skalaer i utgangspunktet, selv om de var like.

**Comment by mimarz** [comment]
Won't fix as we are limited by Token Studio needing to separate these tokens for now
