### ISSUE TITLE
Add padding top and bottom to the Button component

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1726]
When Button has multiple line with text, there should be a top and bottom padding.

![Image](https://github.com/digdir/designsystemet/assets/1464915/06be8af5-4300-4a58-9c2b-c60bed8ab7b7)

**Comment by Barsnes** [comment]
This is blocked by #1696, or should be done in that PR directly.

**Comment by mimarz** [comment]
This might break `Button` used as an "icon button". Make sure to test the stories and judge how it looks. 

Most likely a BREAKING CHANGE for our users as it changes current expected behaviour.

**Comment by mimarz** [comment]
Which spacing token should this padding be @mrosvik ?

**Comment by mrosvik** [comment]
**Small**
padding top and bottom: `spacing-2`

**Medium**
padding top and bottom: `spacing-3`

**Large**
padding top and bottom: `spacing-3`

---

Could this wait until after V1?

**Comment by mimarz** [comment]
> **Small** padding top and bottom: `spacing-2`
> 
> **Medium** padding top and bottom: `spacing-3`
> 
> **Large** padding top and bottom: `spacing-3`
> 
> Could this wait until after V1?

spacing-3 does not work with `medium` `Button` as its forces if bigger in combination with text size.

<img width="322" alt="image" src="https://github.com/digdir/designsystemet/assets/1070981/e12aa1f5-a984-4b9c-a968-1303ef11665f">

**Comment by mimarz** [comment]
@mrosvik Reduced it to spacing-2 for medium, you can have a look here: https://storybook-pr-1910.dev.designsystemet.no/

**Comment by mrosvik** [comment]
LGTM :) 

Large 
![image](https://github.com/digdir/designsystemet/assets/1464915/09562cb1-8b7e-48da-83b2-4af7279cd7c2)

Medium:
![image](https://github.com/digdir/designsystemet/assets/1464915/099bf3d5-4c10-47b9-8b15-8e85b7f29a28)

Small: 
![image](https://github.com/digdir/designsystemet/assets/1464915/e33f8123-f5bb-491d-a041-e9ba31198fa3)
