### ISSUE TITLE
Migrate Storefront to App router

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1748]
https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration

**Comment by Barsnes** [comment]
I have added an `app` folder and started moving over layouts and pages from the `pages` folder.
It is pretty straight forward to migrate to app router, but it is a tedious task.

Only issue I had was to understand how to effectivley use `layout.tsx`, especially in `/bloggen`. The root `/bloggen` has one layout, but it's children, `/bloggen/YEAR/SLUG` should have a different one. I solved this by moving the index of `/bloggen` to a parenthesised folder `(frontpage)`, which then houses the layout, but only for `/bloggen`.

**Comment by mimarz** [comment]
Hmm, if you have time this is something we could use help with @poi33 😊. @Barsnes needs to put this on hold and prioritise some other issues.

**Comment by poi33** [comment]
@mimarz Tror ikke jeg får så mye tid før helgen. Kan være det tar meg en stund før jeg blir ferdig.

**Comment by mimarz** [comment]
> @mimarz i will not have much time before the weekend. Might take me a while before it's done.

Fair enough! Whenever you have the time or want to contribute more. 

We'll see whenever we get around to doing this as its not crucial for V1 but more house cleaning :)
