### ISSUE TITLE
Using `asChild` on `*.Trigger` components should not clone parent styling

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1794]
When using `asChild` on utility/helper components such as `Trigger`, the styling from "default" component should not bleed over to the child component. 

Example of bug: https://codesandbox.io/p/sandbox/frosty-architecture-39tkw4?file=%2Fsrc%2FApp.tsx%3A16%2C30

**Comment by Barsnes** [comment]
I would not call this a bug, but rather a decition we need to make.
As discussed on slack: We will make a rule that only "low level" component such as `Button, will keep their stylings (and other props). 
If we make a component using a lower level component, we remove the underlying element and only render the element the user sends in, with the props we have added.

If they want i.e. a `DropdownMenu` trigger to be a link, they need to use `asChild` deeply:
```tsx
<DropdownMenu.Trigger asChild>
  <Button asChild>
    <Link />
  </Button>
</DropdownMenu.Trigger>
```

**Comment by mimarz** [comment]
> I would not call this a bug, but rather a decition we need to make. As discussed on slack: We will make a rule that only "low level" component such as `Button, will keep their stylings (and other props). If we make a component using a lower level component, we remove the underlying element and only render the element the user sends in, with the props we have added.
> 
> If they want i.e. a `DropdownMenu` trigger to be a link, they need to use `asChild` deeply:
> 
> <DropdownMenu.Trigger asChild>
>   <Button asChild>
>     <Link />
>   </Button>
> </DropdownMenu.Trigger>

Good point! 

`*.Trigger` is more of a utility component that renders as a `Button` as default. If its changed using `asChild` it changes the underlying default rendered component (to `Slot`).
