### ISSUE TITLE
Introduce a `colors` script in our cli

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1886]
With our new token structure we have the feature of auto-generating color scales for `accent` color. 

We want to add the logic for generating the color scales in the cli so we can re-use it several places such as figma plugins, websites or just as pure cli script. 

The color function should have names props for each color definition. When exposed through the `cli`, the color set could be a comma separated string. 

For example `npx @digdir/designsystemet add-theme Altinn --colors "#0062BA, #1E2B3C, ##F45F63, #E5AA20, #1E98F5"`

**Comment by mrosvik** [comment]
Duplicate of #2085

**Comment by mimarz** [comment]
Re-opened as @Thuneer is going to move the logic for colors to `cli/src/colors` and this will be part of #2085

**Comment by mimarz** [comment]
This has been solved
