### ISSUE TITLE
How do we solve inverted componts with new color scale

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1962]
## Components
* **tooltip**

## Problem
We will remove our inverted components and tokens. Will theese components be able to handle this change? This is mostly a problem in Figma

- [ ] Create suggestion in Figma

**Comment by Febakke** [comment]
We will "flip" the scale for `tooltip`meaning that we will use text with high contrast as background and a background color as text. This will solve this issue and give high contrast on the surface and text. 

It should work in code and Figma

**Comment by mimarz** [comment]
Users will solve this by using data-attr `data-ds-color-mode` to scope CSS variables for elements

**Comment by mrosvik** [comment]
This is done in #1849
