### ISSUE TITLE
Combobox - Not possible to deselect and options disappears

### ISSUE THREAD

**Issue by TobiasHansen** [digdir/designsystemet#1982]
### Description of the bug

When using `Combobox` without the multiple option, it is not possible to deselect an picked option. In addition, all other options than the selected option disappears from the dropdown list after you have selected a option, so it is not possible to change options either.

https://github.com/digdir/designsystemet/assets/6777340/2083bb97-fb9c-4ed3-baf0-bce4d914a580

### Steps To Reproduce

1. Go to storybook example for Combobox https://storybook.designsystemet.no/?path=/docs/komponenter-combobox--docs
2. Select an option

**Comment by mimarz** [comment]
Thanks! We'll get on it!
