### ISSUE TITLE
New pattern: Filter

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#199]
### Related issues or relevant information?

Filter-komponent består av 3 core-components: 
(1) Søkefelt 
(2) Filter-valg
(3) [Chip](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=11074%3A68479&t=IpGqsLXUzhhpwgX0-1). 

Vi må vurdere om dette skal lages som en sammensatt komponent av de 3 mindre komponentene.

**Comment by mimarz** [comment]
This is being discussed first: https://github.com/digdir/designsystemet/discussions/2149
