### ISSUE TITLE
Add Designsystemet to Samarbeidsportalen

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2002]
There should be an entrance to Designsystemet from samarbeidsportalen: https://samarbeid.digdir.no/ 

![Image](https://github.com/digdir/designsystemet/assets/1464915/95133529-cd6a-4605-8841-66b9637668f2)

**Comment by mimarz** [comment]
bump, who can fix this? @mrosvik

**Comment by mrosvik** [comment]
Jeg er i dialog med redaksjonen.

**Comment by mrosvik** [comment]
Looks like this has been fixed in the summer. Closing this issue.  https://samarbeid.digdir.no/altinn/portalar-og-brukaroppleving/2485

![Image](https://github.com/user-attachments/assets/a9548466-db9a-428e-a77a-d2d7e60558c1)
