### ISSUE TITLE
Character counter on Textfield component does not update with initial value 

### ISSUE THREAD

**Issue by paal2707** [digdir/designsystemet#2042]
### Description of the bug

When I write a character in the Textfield component the character counter shows the number of positions left correctly. But after I have saved the value and refreshed the page, The text shows up in the input but the character counter shows the incorrect message "Du har 9 av 9 tegn igjen" (the field is already full). If I start editing in the opened field again, it updates after the first character change and behaves as expected.

### Steps To Reproduce

1. Add initial text to Textfield with character counter
2. Load page

### Additional Information

<img width="228" alt="image" src="https://github.com/digdir/designsystemet/assets/68380161/74d8084a-d1d8-4074-b877-b113d1d25c1b">

**Comment by Barsnes** [comment]
Hey, thanks for the bug report! 🐛 
Are you using `defaultValue` to set the initial value of the input?
I tested with `defaultValue`, and it seems to work fine. However, I get the same bug you are describing when using just `value` for the initial input.

**Comment by paal2707** [comment]
I am not using defaultValue because i want the component to be controlled. When page is reloaded this occurs.

**Comment by Barsnes** [comment]
> I am not using defaultValue because i want the component to be controlled. When page is reloaded this occurs.

I understand, would something like this work for you?
[codesandbox](https://codesandbox.io/p/sandbox/controlled-default-value-input-qjcdjf)

```tsx
const DEFAULT_VALUE = "default";

export default function Controlled() {
  const [value, setValue] = useState(DEFAULT_VALUE);

  return (
    <Textfield
      value={value}
      onChange={(e) => setValue(e.target.value)}
      defaultValue={DEFAULT_VALUE}
      characterLimit={{
        maxCount: 9,
      }}
    />
  );
}

**Comment by paal2707** [comment]
> > I am not using defaultValue because i want the component to be controlled. When page is reloaded this occurs.
> 
> I understand, would something like this work for you? [codesandbox](https://codesandbox.io/p/sandbox/controlled-default-value-input-qjcdjf)
> 
> ```tsx
> const DEFAULT_VALUE = "default";
> 
> export default function Controlled() {
>   const [value, setValue] = useState(DEFAULT_VALUE);
> 
>   return (
>     <Textfield
>       value={value}
>       onChange={(e) => setValue(e.target.value)}
>       defaultValue={DEFAULT_VALUE}
>       characterLimit={{
>         maxCount: 9,
>       }}
>     />
>   );
> }
> ```
> 
> _edit: I see that this throws a console error_ 🤔

This wont fix my problem because if you reload the page the state is beeing preserved but not the defaultValue. Also if i set the defaultValue initially to my value, then it throws the error you are referring to. I have added a pull-request with a possible solution. https://github.com/digdir/designsystemet/pull/2056
