### ISSUE TITLE
Tooltip does not work inside Modal

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#2053]
### Description of the bug

Tooltip does not work when placed inside the Modal component.

### Steps To Reproduce

Place a Tooltip inside the Modal component.
Codesandbox: https://codesandbox.io/p/sandbox/goofy-sun-hznv5g

**Comment by Barsnes** [comment]
This might be related to #500

**Comment by TobiasHansen** [comment]
This is still an issue @Barsnes , made a minimal codesandbox to showcase the behaviour of Tooltip in Modal. I played a bit around with the Tooltip-component earlier this week, and I got it working by using the root prop in FloatingPortal. 

https://codesandbox.io/p/sandbox/designsystem-modal-5ctlqr

**Comment by Barsnes** [comment]
> This is still an issue @Barsnes , made a minimal codesandbox to showcase the behaviour of Tooltip in Modal. I played a bit around with the Tooltip-component earlier this week, and I got it working by using the root prop in FloatingPortal.
> 
> https://codesandbox.io/p/sandbox/designsystem-modal-5ctlqr

Hi, add `portal={false}` to the tooltip: https://codesandbox.io/p/sandbox/designsystem-modal-5ctlqr
![image](https://github.com/digdir/designsystemet/assets/14057205/0b829bd9-c76b-48a0-bcdb-78a75d8f875f)

**Comment by TobiasHansen** [comment]
Ah, perfect!

**Comment by Barsnes** [comment]
> Ah, perfect!

I added a not about this in #2053, so we will remember to add it to the documentation later on
