### ISSUE TITLE
Link: Increase offset on the underline with 1px

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2059]
Suggested by @solhell

On characters that go down into the basement like jy and g they almost crash with the underline. To enhance readablity we should increase the offset with one pixel to mitigate this. 

From this:
![Skjermbilde 2024-05-22 kl  13 15 23](https://github.com/digdir/designsystemet/assets/33222679/8b29bb44-1049-46cb-935d-c028e55738be)

To this:
![Skjermbilde 2024-05-22 kl  13 15 37](https://github.com/digdir/designsystemet/assets/33222679/83faf717-f621-4a22-af1e-efe55b118893)

(dont mind the different stroke-width, just a screen issue 🤯) 

- [ ] Fix in Figma
- [ ] Fix in Code

**Comment by Barsnes** [comment]
This will be resolved in #2059, where we have changed from `4px` to `5px`

**Comment by mrosvik** [comment]
Solved in V1.
