### ISSUE TITLE
Add distance between options in inline radio group

### ISSUE THREAD

**Issue by solhell** [digdir/designsystemet#2066]
### Description

When using inline radio group, the current distance is equal between the any label to the radio options the the left and right of this label.
![image](https://github.com/digdir/designsystemet/assets/20128085/97694047-129e-4cb0-8214-5c2a8fdd4718)

Although it is an established design pattern to place the label after the radio, users that have tunnel vision or are using OS-base zoom functionality may become unsure when scanning through several options and the distances are equal.

I suggest to change the distance after the label to --fds-spacing-5, which would look like this:
![image](https://github.com/digdir/designsystemet/assets/20128085/4f0cf769-1406-4d60-b3c0-9120fda18c02)

**Comment by Barsnes** [comment]
Thanks for the issue! 
I see that in figma we have a spacing of 6, so this is a bug in the CSS 
![image](https://github.com/digdir/designsystemet/assets/14057205/6d034fae-3ef0-47bb-87cb-997e032024f3)
