### ISSUE TITLE
Bugs in CSS after migrating to new tokens

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2075]
Things that need to be fixed in CSS after running the beta-to-v1 migrate script.

- [x] Skiplink: 
  - [x] Endre på bakgrunnsfarge til --ds-color-neutral-background-default
  - [x] Endre på tekst til å se ut som i en secondary knapp
- [x] Radio: Fiks styling
- [x] Checkbox: Fiks styling
- [x] Switch: Fiks styling (checkmark should have accent color)
- [x] Tabs - Tab: Fiks fokus styling
- [x] Link: Fiks styling
- [x] NativeSelect color-mode

**Comment by mrosvik** [comment]
Solved in #1849
