### ISSUE TITLE
Decide if we should include label inside the focus indicator for radio and checkboxes

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2080]

**Comment by Barsnes** [comment]
Reading on W3 I see that they have focus around label and element:
https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch-checkbox/
https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox/

**Comment by mrosvik** [comment]
We decided to include label inside the focus indicator for radio and checkboxes.
