### ISSUE TITLE
`init` script for design-tokens

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2084]
As an alternative to our design-tokens template repository we should also provide a `init` or `create` script for our users to create the same `design-tokens` files and generic package.json.

This is a planned feature from us and we have also already had feature request from our users after we unveiled our CLI.

Notes:
- Init script with prompts for things such as:
  - Package name, theme name, npm package for css yes/no 
- Defining theme name would mean we would need to interop with Token Studios internal/private `$theme.json` file. This could be brittle as we have no way of knowing when these are changes, and they also use a random id for references.

**Comment by unekinn** [comment]
As a suggestion for what the init script could be:
- a package `@digdir/create-tokens` which can be run with `npm init @digdir/tokens`
- the package's `package.json` defines a `bin` field pointing to a node script which handles package creation using a template

An example is Vite's [`create-vite` package](https://github.com/vitejs/vite/tree/main/packages/create-vite)

**Comment by mimarz** [comment]
Wicked! Thanks for taking the time to test this @unekinn <3 

Not sure when we'll have the time to take this further. We have some other stuff we need to lands first, but this could deffo be something we could do for the V1 release 🤔  

Now we would only be vulnerable if they decided to change the format, but that can be easily tested :)

**Comment by unekinn** [comment]
[Here's a working prototype init script](https://github.com/unekinn/create-digdir-tokens). I should add some more instructions about the next steps in Tokens Studio, and add package.json initialization (will be quick to to)

If you're interested, I could try to create a PR in this repo.

**Comment by mimarz** [comment]
> [Here's a working prototype init script](https://github.com/unekinn/create-digdir-tokens). I should add some more instructions about the next steps in Tokens Studio, and add package.json initialization (will be quick to to)
> 
> If you're interested, I could try to create a PR in this repo.

![image](https://github.com/digdir/designsystemet/assets/1070981/a8cc8447-3c3c-43ca-9cae-c63587b1e72e)

Wow, really nice work! Just how I imagined! I was also planning on implementing `prompts` for our migrations and the `cli` in general, which i saw you used 👏 

We are still busy with V1 and a lot of underlying stuff we are still working on, so I won't have much time to look to deep into this atm, but you are free to make a PR ofc <3 

We have done a lot of changes to the `cli` in the RC V1 branch (such as using [commanderjs](https://github.com/tj/commander.js) ) so if you want to make a PR for this it needs to be based of branch `feat/tokens-v2`, either way this can be a good starting point! 🏃

**Comment by mimarz** [comment]
Everything related to this should be done based of the `next` branch.

**Comment by unekinn** [comment]
Finalized the package.json and "Next steps" instructions (feel free to comment). Will look into creating a PR next week, probably!
<img width="693" alt="image" src="https://github.com/digdir/designsystemet/assets/910569/a5f410f1-e8fe-412c-b3ab-c8681aca8d14">

**Comment by unekinn** [comment]
Some further ideas that could be explored:
- Under "Customizing the themes", step 4, it would be nice if theme.designsystemet.no could generate the correct theme identifier. Maybe an input field on the page to name the theme, which would also be "saved" in the query params for easy sharing with the share button in the "Kopier tema" popup
- Additionally, it would be nice to allow users to input the theme colors as a part of the wizard

**Comment by mimarz** [comment]
> Some further ideas that could be explored:
> 
> * Under "Customizing the themes", step 4, it would be nice if theme.designsystemet.no could generate the correct theme identifier. Maybe an input field on the page to name the theme, which would also be "saved" in the query params for easy sharing with the share button in the "Kopier tema" popup
Agreed! We had a brief look at this before RC but it means you also need to update the `$theme` with the new name or have to do it manually afterwards in Token Studio, so we just left it as is for now and planned to purse the `init` script way of initialising new design-tokens after RC release.  
> * Additionally, it would be nice to allow users to input the theme colors as a part of the wizard
We have big plans for this already :D #1886 #2085
The idea is for `@digdir/designsystemet` to server as a core for all of Designsystemets logic, and be used across multiple products & implementations!

**Comment by unekinn** [comment]
After a small break, I have updated to the latest CLI version and I'm now happy with the output. I have tested that the generated instructions work in Figma and code. [Here's an example of the generated README.md with next steps](https://gist.github.com/unekinn/c06effb555326d9ea9b248e8794b9601).

I'll now start working on a PR based on the `next` branch!

**Comment by mimarz** [comment]
> After a small break, I have updated to the latest CLI version and I'm now happy with the output. I have tested that the generated instructions work in Figma and code. [Here's an example of the generated README.md with next steps](https://gist.github.com/unekinn/c06effb555326d9ea9b248e8794b9601).
> 
> I'll now start working on a PR based on the `next` branch!

Sweet! 

We have did some changes on the css output and design-tokens yesterday. Haven't updated the template yet, but have a look at it in the `next` branch for latest format. 

Most notably typography has been updated to follow the same token linking structure as colors, so people can assign their own typography and font family per theme.

**Comment by unekinn** [comment]
> We have did some changes on the css output and design-tokens yesterday. Haven't updated the template yet, but have a look at it in the `next` branch for latest format.
> 
> Most notably typography has been updated to follow the same token linking structure as colors, so people can assign their own typography and font family per theme.

Since the script outputs a package.json with reference to the currently published CLI tool, I haven't changed the design tokens structure in my PR, as it would be difficult to test. If you let me know when a new version is published, I'll change the structure to match.
