### ISSUE TITLE
Update docs about RSC and using dot notation

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2087]
Using React Server Components and "dot notation" (`Accordion.Item`) does not work and causes a crash. 

We export all components in full name, so in this use-case our users need to use the full name instead, `Accordion.Item` -> `AccordionItem`.

We should add a note about this in our getting started or maybe a new QA section? 🤔

**Comment by Barsnes** [comment]
This has been added on our ["Bruk"](https://next.storybook.designsystemet.no/?path=/docs/bruk--docs#ssr) page in Storybook.
I'll close this since that page is a part of our documentation. We can open another issue about how our documentation should be structured.
