### ISSUE TITLE
Do we use `aria-errormessage` instead of `aria-describedby`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2089]
When do we add support for `aria-errormessage`, should we even though its not fully supported? 

We are currently using `aria-invalid` in combination with `aria-describedby` which is also an valid option.

Notes:
- https://github.com/w3c/aria/issues/2048
- https://github.com/w3c/aria/issues/2048#issuecomment-1743299817

**Comment by Barsnes** [comment]
Since support is sparse, I think we should wait before implemeting this

**Comment by eirikbacker** [comment]
`aria-describedby` is at least very well supported. Only tip would be to ensure error-message ID is always prepended _before_ help-text-ID in the attribute, so:
✅ `aria-describedby="my-error-id my-helptext-id"`
❌ `aria-describedby="my-helptext-id my-error-id"`

**Comment by eirikbacker** [comment]
Closing for now as `aria-errormessage` support is too low
