### ISSUE TITLE
Error with combobox virtualization

### ISSUE THREAD

**Issue by PieNappl3** [digdir/designsystemet#2106]
### Description of the bug

when virtualization is on in combobox and you try searching for a value the page crashes
issue is also present in storybook https://storybook.designsystemet.no/?path=/story/komponenter-combobox--virtualized
and in storybook for thousands of options

seems to not be bugged if there are few enough options so might be related to having more than 1 virtual page

### Steps To Reproduce

create combobox with a lot of comboboxoptions
enable virtualization
start typing to search for an option

**Comment by Barsnes** [comment]
Hi, I have noticed this as well - but have not gotten around to make an issue for it yet.
I am waiting for #2095 to be merged before I will start work on this.
