### ISSUE TITLE
Adjust base colors in darkmode

### ISSUE THREAD

**Issue by Thunear** [digdir/designsystemet#2120]
Adjust the base colors in dark mode to fit better visually.
* Reduce the saturation on certain color ranges to make the color less aggressive.
* Reduce the lightness using linear interpolation to make the color appear lighters and fit better with the darker backgrounds.
* Make a system to ensure contrasts are beeing followed.

![Image](https://github.com/digdir/designsystemet/assets/13560642/43aedf42-832f-49e9-8202-650bf122c799)

**Comment by mimarz** [comment]
Was this fixed in #2370 ? @Thunear

**Comment by Thunear** [comment]
This was fixed a bit earlier when we started flipping the colors in dark mode, so this issue is no longer relevant.
