### ISSUE TITLE
What components should have `*.Root`

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#2123]
Some components like `Pagination` currently have `Pagination.Root`.
We should try to streamline this across other components to keep our api cohesive.

Some contenders to get `*.Root` are
- Tabs
- ToggleGroup
- Popover
- DropdownMenu
- Accordion

Edit: @mimarz 
Saved for later if requested:
- Textfield/area (if we want them to be composed) - will also include switch, radio, etc.

**Comment by mimarz** [comment]
This will be released in #2130
