### ISSUE TITLE
Convert to use `exports` in our packages

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2132]
We have tested using [exports](https://nodejs.org/api/packages.html#conditional-exports) in `theme` and it works very well. 

Suggest we convert our remaining packages to use the same syntax.

This will also give us the added benefit of using [subpath-exports](https://nodejs.org/api/packages.html#subpath-exports) for example for our components.

**Comment by Barsnes** [comment]
I have done this for `react` in #2130, with
```
"exports": {
    ".": {
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js",
      "types": "./dist/types/index.d.ts"
    }
  },
```

Seems to work fine

**Comment by Barsnes** [comment]
I don't see why we would need to do this for our css package, we won't gain anything from afaik.
as for exporting components, I think we should leave it as I have done above, but we can add a separate export for `hooks` and `utilities`, or both under the same export.

**Comment by mimarz** [comment]
Looks good how it is now :)
