### ISSUE TITLE
Forslag til detaljering av Skip Link

### ISSUE THREAD

**Issue by solhell** [digdir/designsystemet#2140]
### Description

Jeg observerer ofte at Skip Link blir plassert helt oppe til venstre i løsninger som bare bruker deler av skjermbredden.
Dette gjør den vanskeligere å oppdage, selv om den har et tydelig design. Et eksempel kan dere se på politiet.no.
![image](https://github.com/digdir/designsystemet/assets/20128085/2508933f-0d30-467a-a36c-46ce54c613f6)

Foreslår at dere i beskrivelsen av SkipLink-komponenten tydeliggjør at denne bør plasseres innenfor hovedspalten for innholdet, eventuelt i hele skjermbredden slik de gjør på regjeringen.no.
![image](https://github.com/digdir/designsystemet/assets/20128085/8fb6cebe-e2c6-43c2-bc90-c498a1162507)

**Comment by Febakke** [comment]
Godt forslag @solhell  👏  Vi har gjort noen endringer i forbindelse med versjon 1. Vi fjerner blant annet den gule signalfargen. Her er hvordan den nye vil se ut etter at vi sentrerer teksten. 
![Image](https://github.com/digdir/designsystemet/assets/33222679/3f12e94c-4634-4ec3-99db-3df142de5872)

Vi kommer til å endre slik at teksten blir midtstilt. Men har du noen innspill på designet? 

Vi bruker nå en sekundærknapp hvor knappen har tastaturfokus. Det ser kanskje litt rart ut i akkurat denne konteksten. Her er et par andre muligheter. 

Tertiærknapp uten tastaturfokus
![Image](https://github.com/digdir/designsystemet/assets/33222679/98a0ad72-8b84-4275-b354-89965b929eca)

Link uten tastaturfokus
![Image](https://github.com/digdir/designsystemet/assets/33222679/f40e3708-f8a8-4012-b113-7d60ef09bb70)

**Comment by mrosvik** [comment]
@Febakke :
@Thuneer har another suggestion to the design :)

**Comment by Thuneer** [comment]
My suggestion is to change the background color to accent-suface-hover to make the whole section stand out more against background-subtle. I also liked using the `Link` design inside the container. It makes the design a bit cleaner. I also changed the text color to accent-text-default to make it stand out a bit more.

![Image](https://github.com/user-attachments/assets/ae91ff99-d359-4a9d-88a2-4d47c711aa2e)

**Comment by solhell** [comment]
Støtter forslaget til Thuneer her :)
