### ISSUE TITLE
How to handle multiple JSON files in Temavelgeren

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#2143]
Since we have added border radius to Temavelgeren, we need to figure out how we can best allow users to copy contents.
The JSON we give the user should be split between multiple files, for colors, typography and sizes.

![image](https://github.com/digdir/designsystemet/assets/14057205/5d9365a2-d2ae-4e0a-9333-5a7784f034e0)

Possible solutions:
* Generate a zip file containing all json files
* Copy each file individually
* Give users a CLI command they can run

I think it would be best to give a zip file, so both developers and designers can easily drop the files where they need them.
I believe this should be possible to do with a server action.

**Comment by mimarz** [comment]
Agreed. 

I think options 1 and 3 are possible and those we should aim for. 

We can use the same approach @unekinn started with in the init script with having a portable way of generating the `design-tokens` files given x input.

Then we can use them in both terminal and apps.   

> ...
> Possible solutions:
> 
> * Generate a zip file containing all json files
> * Copy each file individually
> * Give users a CLI command they can run
> 
> I think it would be best to give a zip file, so both developers and designers can easily drop the files where they need them. I believe this should be possible to do with a server action.

**Comment by mrosvik** [comment]
This is solved 🎉 #2290
