### ISSUE TITLE
Theme builder color-info-modal HSLuv values are not HSLuv

### ISSUE THREAD

**Issue by Camulos** [digdir/designsystemet#2156]
### Description of the bug

HSLuv values seem to be HSL and not HSLuv

@øyvind

### Steps To Reproduce

 Go to https://theme.designsystemet.no/
Copy HEX-color value
Use online color tool to get the HSLuv value
compare the value with the value in the theme-builder.

```[tasklist]
### Tasks
```

**Comment by mimarz** [comment]
@Thuneer has fixed this
