### ISSUE TITLE
AccordionItem with defaultOpen set to true initially shows as closed, but with contents overflowing

### ISSUE THREAD

**Issue by Hifoz** [digdir/designsystemet#2178]
### Description of the bug

If you have an AccordionItem with `defaultOpen` set to true, it will for a second show the accordion-item as closed (height set to 0), but with the text visible (overflowing), when a user first enters the page.

I've also noticed that sometimes when you open a closed accordion, the text will be visible just before the height of the accordion-item is updated.

Setting `overflow: hidden` on `.ds-accordion__item` or `.ds-animate-height` does seem to fix the overflow-issue, but the accordion still seems to be closed until the content is hydrated when `defaultOpen` is set to true. Our application does use NextJS, so its possible that this is only an issue when using serverside-rendering, as a purely clientside-rendered app would likely set the height correctly on first render.

### Additional Information

Example: https://virksomhet.brreg.no/nb/oppslag/enheter/974760673
![image](https://github.com/user-attachments/assets/4de5c628-0b0e-4332-8e68-4f931f3d51a5)

**Comment by mimarz** [comment]
Thanks for reporting this! 

Have tried declaring `use client` in the component you are using the `Accordion`? 

This is always the bad side of using js to handle animation, which is needed for correct animation speed depending on content. 

We do want to avoid layout shift, but we are using React Context inside the `Accordion` also making it hard to alternatively have RSC. 🤔

**Comment by Hifoz** [comment]
Our Accordion is within a client-component, and not an RSC, so i don't think that should be an issue. 

From what i can see from debugging in the browser and looking at the [AnimateHeight-component](packages/react/src/utilities/AnimateHeight/AnimateHeight.tsx), it sets style="height: 0" on the `.ds-animate-height`-div  initially, regardless of whether it is set to defaultOpen or not, since the height-state gets initialized as 0.

Could it be a possible solution to initialize the height as undefined, and then set it to the correct height (like you do in the [resizeObserver](https://github.com/digdir/designsystemet/blob/cf7ed413aaf6f3ecafb076c0d0fe1e2675b8157b/packages/react/src/utilities/AnimateHeight/AnimateHeight.tsx#L36)) in a useEffect or something like that? From what i can tell, both the open and closed states looked correct when height was not set.
