### ISSUE TITLE
Combobox - Not possible to close the combobox by clicking on the arrow button

### ISSUE THREAD

**Issue by sharizard** [digdir/designsystemet#2180]
### Description of the bug

It is not possible to close the combobox by clicking on the arrow icon button in the combobox field. The combobox can be closed by clicking outside the combobox, using the keyboard, or by choosing a value.

I've attached a screen recording where I compare the behaviour of Digdir next combobox and Aksels (NAVs design system) combobox.

https://github.com/user-attachments/assets/18ce4436-7263-499a-ac16-51775f75950e

### Steps To Reproduce

1. Go to the combobox component in the designsystem (latest or next): https://next.storybook.designsystemet.no/?path=/docs/komponenter-combobox--docs
2. Open the combobox by clicking on the arrow down icon
3. Try to close the combobox by clicking on the arrow up icon

**Comment by mimarz** [comment]
Thanks for reporting this! 

We'll have a look at this after summer vacation.
