### ISSUE TITLE
It should be possible to provide a title for the close button in the Modal component

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystemet#2195]
### Description of the bug

The title of the close button in the modal is hard coded and there is no way to change it.
![image](https://github.com/user-attachments/assets/8c33697b-0382-412d-becb-efb8131f8083)

### Steps To Reproduce

1. Add a `Modal` component in some React app
2. Observe that there are no props to set the title

**Comment by Barsnes** [comment]
This has been resolved in the [next branch](https://github.com/digdir/designsystemet/pull/2130/commits/8c42546d2ba53ae18b01690a2733d88fbc29b1d5)
