### ISSUE TITLE
Artikkel om begreper under God praksis

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2208]
Våre kjære innholdsdesignere Gørild og Dorte har gjort et fantastisk begrepsarbeid som er veldig relevant. Dette er begreper vi har hatt mange diskusjoner om. 

> Vi har søkt og sammenlignet med hva andre virksomheter bruker der vi har kunnet, og har sjekket definisjoner både på norsk og engelsk.Med denne anbefalingen håper vi at knapper og navigasjonselementer kan bli like i alle produktene våre. @Ildest 

I tillegg til at dette skal inn begrepskatalogen, ønsker vi at det publiseres en artikkel på designsystemet.no under "God praksis" > "Innholdsarbeid" > "Begreper". 

![Image](https://github.com/user-attachments/assets/61d2f8b0-654a-4438-8c83-f1aae666f7e7)

**Comment by Ildest** [comment]
Jeg har skrevet et utkast til artikkelen i dag @mrosvik. Har sendt den til gjennomgang hos Dorte nå, så legger jeg den til her etterpå. God helg!

**Comment by Ildest** [comment]
Hei @mrosvik. Her er artikkelen om anbefalte begreper :-).

https://digdir.sharepoint.com/:w:/s/bod-bbo/EbT7et9LH55Kpz-5OqpDhdoBUeQyZb_bBrHMGYUsj-2tBw?email=marianne.rosvik%40digdir.no&e=gD68hg

Si fra om du ikke får tilgang til filen, så laster jeg ned en kopi til deg.
