### ISSUE TITLE
Mulig liten feil og forbedringspotensiale i Modal

### ISSUE THREAD

**Issue by solhell** [digdir/designsystemet#2215]
### Description of the bug

I Modal-komponenten er det første elementet 
`<span data-type="inside" tabindex="0" aria-hidden="true" data-floating-ui-focus-guard="" style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: fixed; white-space: nowrap; width: 1px; top: 0px; left: 0px;"></span>` 

Her stusser jeg litt over at `tabindex` er satt til 0, da dette medfører at dette tomme span-elementet blir et steg i Tab-rekkefølgen. Jeg mistenker at formålet med elementet er å sikre at fokusplasseringen havner på riktig plass når modal åpnes, men da holder det å sette `tabindex="-1"` - det gjør elementet fokuserbart med script, men det blir ikke en del av Tab-rekkefølgen. Og uten at jeg helt kjenner koden, kan det da hende at `data-floating-ui-focus-guard=""` kanskje blir irrelevant?

I samme slengen: kunne ikke style-info blitt lagt i en CSS-klasse? Denne er jo f.eks. også aktuell i Drawer-komponenten som er på vei.

### Steps To Reproduce

https://storybook.designsystemet.no/?path=/story/komponenter-modal--preview

**Comment by Barsnes** [comment]
Hei, denne `span`en kjem frå https://floating-ui.com/docs/floatingfocusmanager, det ligger også ein i bunn av modalen.
Når du tabber til denne vil fokus flytte seg automatisk, så den får aldri fokus

**Comment by eirikbacker** [comment]
Firefox fanger tab-fokus nå, så kan være vi kan fjerne foucs mananger helt :)
