### ISSUE TITLE
Issue with text color for success and danger

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2217]
Tekst `success/contrast-default` blir forferdelig oppå bakgrunn `success/base-default`. Vi bør vurdere en mørkere grønnfarge og oransjfarge for å få hvit tekst.

![Image](https://github.com/user-attachments/assets/132a776e-b60d-4c23-a07a-4c75658ca7be)

**Comment by Thuneer** [comment]
Gjorde den grønne og oransje base fargen litt mørkare for at verkøyet skal velge kvit som kontrastfarge.
Ligger ute på next versjonen av temavelgeren: https://next.theme.designsystemet.no/

**Comment by mimarz** [comment]
Fixed in https://github.com/digdir/designsystemet/commit/49af0ef32aa879ac7065f4c66862679231b05945
