### ISSUE TITLE
Illustrations for new components

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2225]
We need illustrations for some new components:
- Avatar
- Badge
- Breadcrumb

----

- [x] Create illustrations
- [x] Update the component-overview with links to the new components

----

![Image](https://github.com/user-attachments/assets/7f8b0fed-771d-4361-8cf6-06343d0d4ef0)

**Comment by Barsnes** [comment]
Needed in #2220

**Comment by Thuneer** [comment]
I added the 3 images to the storefront. Looks like the Avatar component is not ready yet, so I commented out that entry in the `component-list.ts` file.

Is this Ok @Barsnes, and we can close this issue?

**Comment by Barsnes** [comment]
> I added the 3 images to the storefront in [this](https://github.com/digdir/designsystemet/commit/34c05f0a1289edf23de4b880086a5944d3efe387) commit. Looks like the Avatar component is not ready yet, so I commented out that entry in the `component-list.ts` file.
> 
> Is this Ok @Barsnes, and we can close this issue?

Yes looks good, we will have to put this into the pipeline for new components.
Let's add Avatar when it is done 👍🏻
