### ISSUE TITLE
How should we support typography stacking? (Primitive component)

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2258]
## Design guidelines
We should start with defining what we want to support. And do some research on spacing, sizes and viewports.

## Resources

- https://every-layout.dev/layouts/stack/

**Comment by Barsnes** [comment]
In #2295 we briefly discussed this in [the comments](https://github.com/digdir/designsystemet/issues/2295#issuecomment-2298721061)

**Comment by eirikbacker** [comment]
Closing as this is a duplicate of #2492
