### ISSUE TITLE
Update theme-builder to provide multiple sources for exporting theme

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2271]
With the introduction of typography tokens its quite cumbersome to copy-paste json files from theme-builder and even generate new themes.

Update the theme-builder to provide two different options for exporting to json design-tokens. 

- Command-line snippet for generating json design tokens.
- Download zip with json design tokens. 
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2269
- [ ] https://github.com/digdir/designsystemet/issues/2272
- [ ] https://github.com/digdir/designsystemet/issues/2334
```

**Comment by mrosvik** [comment]
Done
