### ISSUE TITLE
Add disabled buttons to pagination when on first or last page

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2282]
Aligning this component when you are on page one seems wrong when its not centered.. We should concider adding a disabled button to make this clearer

- [x] test in Figma

## How to solve in Figma
We see two ways of solving this. 
1. Add new variants to the component for disabled back and forward buttons. 
  - Pros: Easy for designers to switch between active and disabled states
  - Cons: More settings in the components and more variants. Might be a little excessive.    
2. Keep as is, but add examples with disabled back and forward buttons. 
  - Pros: The component wont need any more variants and it is easy for designers to change the state of the button them selves
  - Cons: We cant be sure that designers see the guidelines and examples and might cause confusion when delivered to development.

**Comment by Barsnes** [comment]
Posten does this, always shows the "Forrige" button:
![image](https://github.com/user-attachments/assets/fa7a40d1-513c-44f6-b0df-efd5888390a6)
Buttons 2, 3, 4 are not disabled here, they just look like that

**Comment by Viveca24** [comment]
We decided to go for alternative number 2 and changed the examples in Figma, so that the previous and next button is disabled when on the first or last page. We decided not to go with alternative number 1, because we did not want to add more complexity to pagination in Figma.

**Comment by Febakke** [comment]
LGTM 😎
