### ISSUE TITLE
Add icon to our `ValidationMessage` component

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2300]
We should follow our own guidelines. When working on the pattern for errormessages we concluded that you should use icon to use more than a color to differentiate from labels and other textelements. 

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2308
- [ ] https://github.com/digdir/designsystemet/issues/2309
- [ ] https://github.com/digdir/designsystemet/issues/2310
```

**Comment by mimarz** [comment]
This needs to be done after [2444](https://github.com/digdir/designsystemet/issues/2444)
