### ISSUE TITLE
Are the icon we have available now good enough when in a small size?

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2308]
- [x] Test different icons and bullet points
- [x] Compare and evaluate whether we need an icon next to the validation message
- [x] Test an icon with a thicker exclamation mark in the small version

**Comment by Viveca24** [comment]
New icon suggestion:
![Image](https://github.com/user-attachments/assets/bc547641-8351-4892-bcef-9e27e7151eff)

I suggest that the ValidationMessage includes an icon alongside it, as adding an icon provides an extra visual cue to the user that something requires their attention. After investigation, I prefer the triangular version, as it appears to be a clearer warning shape than the circle. For smaller versions, I recommend making the exclamation mark thicker to ensure better visibility within the icon.

**Comment by mrosvik** [comment]
Enig! Om de ikke ser utropstegnet, så vil de se trekant-formen, som er et varsel-symbol i seg selv.
