### ISSUE TITLE
Chip group: Should it wrap?

### ISSUE THREAD

**Issue by eirikbacker** [digdir/designsystemet#2315]
Today, chip groups does not wrap, and they do not get a horizontal scroll container, causing the whole page to potentially scroll horizontally if there is more chips than space.

I understand the no-wrapping-solution is inspired by a pattern found in [Google Material 3](https://m3.material.io/components/chips/guidelines),  but their chips also have the ability to wrap as seen in the [filter section](https://m3.material.io/components/chips/guidelines#96b78af6-fb40-47fd-9c51-1496251f3378).

I suggest we set our chips to wrap by default, as scrolling in two directions is [considered harmfull for accessibility](https://www.w3.org/WAI/WCAG22/Understanding/reflow). Furthermore, the horizontal scrolling pattern works well if chip area covers the whole screen width, which is rarely the case on desktop where filters are typically places in a sidebar or in a centered main layout.

**Comment by mrosvik** [comment]
Meeting 26.08.24

Chips in group should wrap.
