### ISSUE TITLE
Missing Divider component in Figma - and, should it have variants or not?

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2320]

**Comment by mrosvik** [comment]
Discuss this when @Thuneer is back.

**Comment by mrosvik** [comment]
@eirikbacker : As discussed with @Thunear, we need subtle and default. Subtle for tables, modal, etc. In articles more visible. Could you share your thoughts about this @eirikbacker ?

**Comment by eirikbacker** [comment]
Hello! Table lines are not really "dividers" - these are borders of the table rows - same goes for every border - for instance a border of a modal header or modal footer :) This is indeed from a technical standpoint, but I would presume this is quite similar in Figma? :)

**Comment by eirikbacker** [comment]
After talk with @Thunear ; lets keep only Subtle for now :)

**Comment by eirikbacker** [comment]
Will be fixed by #2313
