### ISSUE TITLE
Missing Button loading state in Figma

### ISSUE THREAD

**Issue by eirikbacker** [digdir/designsystemet#2330]
Button has a built in loading state, but there is no sketches for it in Figma? :)

**Comment by Viveca24** [comment]
I have created and tested an animated spinner for the `button's` loading state in Figma.

What has been done:
- [ ] Animated the spinner for the button's loading state.
- [ ] Designed the animated spinner for all button sizes (small, medium, large) and states (default, hover, active, disabled).
- [ ] Tested across all states (default, hover, active, disabled) and sizes to ensure consistent behavior and appearance.
- [ ] Created examples in Designsystemet Core UI Kit

**Comment by Viveca24** [comment]
I'm not sure if having multiple lines in a button is considered a good UX practice. But I would like to know what you think about the placement of the spinner: should it be centered in the middle of the button, as shown in the image, or placed next to the first line of text when the button contains two lines? @mrosvik & @Febakke 

![Image](https://github.com/user-attachments/assets/8830a906-2670-4eac-9951-a75ae905c147)

**Comment by mrosvik** [comment]
In Storybook it looks like the icon and the loader is centered. I think we should keep it this way, since the padding above text is very small, and the loader will not be aligned with the first line of text. 

![Image](https://github.com/user-attachments/assets/bcde5c59-b9f6-47ff-86f0-29026cc087d0)

![Image](https://github.com/user-attachments/assets/b5c004fd-bc0a-4b25-bf34-05d61482bcf6)

**Comment by Viveca24** [comment]
I have implemented a spinner that supports all colors, utilizing the same 'sub-tokens' for consistency across different colors. 

Background: `color.<variable>.surface-default`
Stroke: `color.<variable>.border-default`

![Image](https://github.com/user-attachments/assets/32361351-0ed8-4785-a3a0-e22c18dd1507)

**Comment by Febakke** [comment]
Skal spinner være synlig på hover? Vi har satt opp prototypingsoppførsel på button komponenten og ser ut til å ikke fungere så bra med spinner. Det gir kanskje ikke mening at en knapp med loader får hover? 

Alternativer:
- Legg til spinner på alle states?
- La være as is, vil se litt buggy ut i prototyper
- Lagg spinner button som egen variant hvor den ikke er koblet til hover med prototyping

![Image](https://github.com/user-attachments/assets/874c8701-f643-4561-bbc6-14ef7b37357f)

**Comment by mrosvik** [comment]
Vi går for alternativ 2: La være as is, vil se litt buggy ut i prototyper. Vi kan evt. utbedre dette senere ved behov.
