### ISSUE TITLE
Create a visual test site in our Figma file

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2347]
We need a page in our Figma file we can use to test that we did not break anything. This would be very handy before we publish new versions so that we can see that we are not breaking anything. This could be done by making one or multiple examples with all of our component and make a copy or take a screenshot. (If it is a copy we need to detach all components to have it as a reference)

You should be able to test
* All overrides are still there
* Scaling works as intended

**Comment by Viveca24** [comment]
We have conducted visual testing, to ensure that we haven't broken any functionality or styling of our components. 

We have examined the following: 
**Overrides** 
Confirmed that all overrides still function as intended. 
**Scaling** 
Ensured that the scaling of components works as expected, without any distortion

**Comment by Viveca24** [comment]
This is done in [Figma](https://teams.microsoft.com/l/message/19:meeting_NDBmMDU0ZTctY2VhMy00MThiLThmZjItMzc0NTZjNmQ0MTI3@thread.v2/1731333582733?context=%7B%22contextType%22%3A%22chat%22%7D). 

We need to fix #2769 to make sure the visual test is correct in future updates.

**Comment by Viveca24** [comment]
This is done in [Figma](https://teams.microsoft.com/l/message/19:meeting_NDBmMDU0ZTctY2VhMy00MThiLThmZjItMzc0NTZjNmQ0MTI3@thread.v2/1731333582733?context=%7B%22contextType%22%3A%22chat%22%7D). 

We need to fix #2769 to make sure the visual test is correct in future updates.
