### ISSUE TITLE
Typography classes: Auto-generating or not? 

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2353]

**Comment by Barsnes** [comment]
I don't see how we can easily get a 1-1 with Figma and css if we don't autogenerate this.
If we autogenerate classes based on settings that come from Figma, we make sure these are always in sync, and makes it easy for consumers to use typography classes wherever they want to.

Another plus is that we can expose a script that also does this for our consumers, should they want to change anything about typography

**Comment by mimarz** [comment]
This was solved in #2429
