### ISSUE TITLE
Create gh action for adding new issues to project

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2365]
Not all new issues are automatically added to the project which results in sometimes being missed by the team.

This is due to limitations on workflows in the project due to current pricing plan.

We can however solve this by using gh actions.

https://github.com/Altinn/app-lib-dotnet/blob/main/.github/workflows/add-to-project.yml

**Comment by Barsnes** [comment]
Action has been added, but needs a new `github-token` that has permissions to move issues to the project

**Comment by mimarz** [comment]
This works now that the PAT was approved. Tested and working on issue #2394
