### ISSUE TITLE
Test primary, secondary og accent color concepts

### ISSUE THREAD

**Issue by Thunear** [digdir/designsystemet#2373]
In color systems it is common to have 2 bright colors, often called primary and secondary that compliment eachother in the UI.
I want to test if our "accent" color is enough after getting feedback from UDIR and Mattilsynet,

Lenke til Figma [her](https://www.figma.com/design/V4dzf3m1sapmU048OQnu7L/Arbeidsomr%C3%A5de%3A-Felles-komponenter?node-id=5738-17059&t=xky5VLZOeuqUNrMS-1).

![Image](https://github.com/user-attachments/assets/08a69883-5ecd-4aa1-b1a1-85f3db020949)

**Comment by Thunear** [comment]
**Bytte frå primary og Secondary til Dominant og Complimentary**

For å unngå forvirring mellom primær- og sekundærhandlingar i komponentene våre, kan det sikkert vere lurt å finne andre navn på fargene våre som bevarer betydningen, men skapar klarere skille.

![Frame 158](https://github.com/user-attachments/assets/3c7c0f7a-a5c4-44d1-865b-5aab057518f4)

**Comment by Thunear** [comment]
**Fargelegging av komponentar**
Me tilbyr brukaren fargane Dominant, Complimentary, Accent, Neutral og x antall Støttefargar. Når ein ser på andre offentlige nettsider og profilar, så er det veldig ulikt kva fargar som treng å vere tilgjengelig på dei forskjellige komponentane. Ei nettside vil kanskje kun ha ein Dominant og Neutral knapp, mens ei anna vil ha ein Dominant og Accent knapp. Me kan ikkje tilby alle fargane på alle komponentane, men det hadde vore fint om brukaren enkelt kunne ha koble på ein farge ved behov.

Forslag:
- Designsystemet tilbyr visse fargar per komponent (ulike fargar per komponent) som følger våre anbefalte mønster og retninslinjer.
- Designsystemet tilbyr ein enkel måte og utvide ein komponent til å ta i bruk alle fargane. (Data attributt i kode og bytting av tema i figma (?))

**Eksempel-scenario med Button:**
Me finner ut av Button trenger Dominant, Accent og Neutral som standard fordi dette er mykje brukt. Då tilbyr me desse fargane som standard som brukaren kan bytte mellom med  Color proppen. Ønskjer brukaren Støttefarge 2 på knappen sin så kan denne enkelt legges til og komponenten forstår korleis den nye fargen skal integreres i komponenten.

![Frame 158](https://github.com/user-attachments/assets/dc083abb-de6b-4c53-9a63-cd5b3ce7866d)

**Eksempel-scenario med Checkbox:**
Me finner ut av Checkbox trenger Neutral og Accent som standard.

![Frame 159](https://github.com/user-attachments/assets/b1f40085-3e67-4243-b75c-f4cd1b216416)

**Eksempel-scenario med Card:**
Me finner ut av Card trenger Blank og Subtle.

![Frame 160](https://github.com/user-attachments/assets/d62a102a-c2b4-45dd-bc7b-493a695fe073)

**Comment by Thunear** [comment]
**Bruk av blå som primærfarge for Digdir og Tilsynet**

I det eksisterande fargesystemet så har me satt blå som Accent farge for Digdir og Tilsynet. Dette passer egentlig ikkje med profilene deira. Dette blir enda tydligare når me begynner med begrep som `Dominant `og `Complimentary`. Eg tok blåsvart og blå frå [profilen ](https://profilveileder.digdir.no/visuell-profil/farger/109)til Digdir som eg satt til `Dominant` og `Complimentary`. Dette syns eg fungerer mykje bedre. Den gule og røde fargen frå profilen har me hatt mykje utfordringar med, så desse tenker eg kan fungere som støttefargar.

**Eksempel på farger for Digdir:**

![Frame 161](https://github.com/user-attachments/assets/57d01c73-50d3-4c4c-9f36-30f0f3af5a64)

**Comment by mimarz** [comment]
We will have a meeting on this week 39 to discuss further.

**Comment by mrosvik** [comment]
We decided to have main and support colors, and make it flexible for the user to add as many support colors as they need.
