### ISSUE TITLE
aria-describedby connected to fieldset is not supported by screen readers

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2386]
When adding a description on `fieldset`, `radiogroup`, `checkboxgroup` it is added to the `fieldset` element using an `aria-describedby`. This is not standard HTML, and not well supported by browsers/screen readers. 

Firefox and chrome/VoiceOver: Ignores description
Safari/VoiceOver: Overwrites all `aria-descibedby` inside the fieldset. 

NVDA/chrome: Works as excpected

We have not yet tested with JAWS

![Image](https://github.com/user-attachments/assets/df1ff88c-4d62-4629-af5e-a57fd65bd8e1)

**Comment by mimarz** [comment]
Relevant issue which is the basis for todays implementation: #519

**Comment by eirikbacker** [comment]
W3C actually mentions themselves that `aria-describedby` should not be used on non-interactive elements: https://www.w3.org/TR/using-aria/#label-support

I a fieldset has a related error message, the `aria-describedby` be set to _all_ child inputs and point to the same message component. Note that the error message ID should then be placed _before_ the ID pointing to the inputs individual description (`aria-describedby="id-of-fieldset-error id-of-input-description"` has good support for containing several IDs)
