### ISSUE TITLE
Radio buttons: missing margin on error message when hidelegend is set to true

### ISSUE THREAD

**Issue by frikkfelix** [digdir/designsystemet#2406]
### Description of the bug

When `hideLegend={true}` on Radio.Group, there is no spacing between the radio buttons and the error message.

### Steps To Reproduce

1. Add a Radio.Group and set hideLegend to true
2. Set error prop on Radio.Group

**Comment by Barsnes** [comment]
Here is a direct link to a story showing that the error message does not have spacing above it.
https://next.storybook.designsystemet.no/?path=/story/komponenter-radio-group--preview&args=error:Ein+error;hideLegend:!true&globals=theme:Dark

I can't seem to reproduce it where the spacing is removed between radio buttons as well.

**Comment by mimarz** [comment]
We have planned a revision of CSS for `Radio` so we'll have a look at this when we do this.

**Comment by eirikbacker** [comment]
Fixed by #2607
