### ISSUE TITLE
`Dropdown.Heading` API

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#2439]
See discussion: https://github.com/digdir/designsystemet/pull/2432#discussion_r1763141759

>Er litt rart å ha en Heading, men at sizes følger Paragraph - at det ikke matcher med Heading-hierarkiet man kjenner igjen i Figma, men dette kan kanskje bli en egen oppgave.
Også litt rart å ikke kunne sette level. Tenker - dersom vi kaller noe *.Heading, burde det extende Heading-komponenten

**Comment by mimarz** [comment]
I suggest `Dropdown.Heading` extends `Heading`. 

`Dropdown.Heading` is just the recommended defaults for use of `Heading` in the context of a `Dropdown`

What do you guys think? @eirikbacker @Barsnes

**Comment by mimarz** [comment]
This is no longer relevant as we don't have a `Heading` component anymore.
