### ISSUE TITLE
Swap naming order for Paragraph variants and size?

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2441]
We have currently named paragraph variants in the current order (which is a bit unintuitive?): 
```
paragraph-md
paragraph-short-md
paragraph-long-md
```

Suggest changing order making it easier to choose which variant to use:
```
paragraph-md
paragraph-md-short
paragraph-md-long
```

This naming order affects design-tokens, figma variables and CSS variables.

**Comment by Barsnes** [comment]
I support this. 
It plays nicely as it is **component -> size -> variant**

**Comment by mimarz** [comment]
We'll have to come back to this as we need `paragraph-short` and `paragraph-long` in fullname to support composing of these typography styles in CSS.

**Comment by mimarz** [comment]
withdrawn
