### ISSUE TITLE
Rename `ErrorMessage` to `ValidationMessage`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2444]
Clearer intent of use so that it can support both `invalid={true}` and `invalid={false}` - making it easy to confirm that a input is valid as well - not only errors

```[tasklist]
### Tasks
- [x] Rename component in Figma
- [x] Rename component in React+CSS
```

**Comment by mimarz** [comment]
We decided to do this in todays daily with team.

**Comment by Barsnes** [comment]
in progress for react
