### ISSUE TITLE
Rename Paragraph long and short and consider wether this is component props at all

### ISSUE THREAD

**Issue by eirikbacker** [digdir/designsystemet#2445]
Today we have `Paragraph`, `Paragraph variant="short"` and `Paragraph variant="long"`.
This means our consumers can make any Paragraph _component_ short or long.

I understand we need short and long _in context_ of i.e. text inside a Card, but I'm unsure wether we want Paragraph component aka. body text to be varying in line height, breaking the typographic flow. 
I suggest we make a distinction between what is a text _style_ and what is a typography _component_.

Also, `variant="long"` and `variant="short"` is a bit confusing for me - may be personal opinion, but could `density="compact"` and `density="loose"` better? ☺

**Comment by mimarz** [comment]
replaced by [2503](https://github.com/digdir/designsystemet/issues/2503)
