### ISSUE TITLE
Rename `DropdownMenu` to `Dropdown`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2446]
Clearer intent and expected use in terms of supported features in regards to a11y, kb etc.

Related to #2221

```[tasklist]
### Tasks
- [x] Rename in Figma
- [x] Rename in React+CSS
```

**Comment by mimarz** [comment]
We decided to rename this in todays daily meeting

**Comment by Barsnes** [comment]
This was renamed in react and css in #2432

**Comment by Febakke** [comment]
Fixed in Figma
