### ISSUE TITLE
How do we solve interconnected component props?

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2453]
Work in progress writing description, but will outline different approaches we have tried and potential other ways of solving inter-connected component props in React.

1. `.Root`
2. `.Context`
3. "Hooks" instead of `Context`, like react-aria [useTextfield](https://react-spectrum.adobe.com/react-aria/useTextField.html)

Notes:
- Should our othermost `.Context` represent the component context or something else?
- Can we get away without using React Context?
- `.Context` is used in two different way currently.
- https://github.com/digdir/designsystemet/pull/2432#pullrequestreview-2312554652
- https://designsystemet.slack.com/archives/C07K7NEKXEW/p1726656413211339

**Comment by eirikbacker** [comment]
Også relevant: https://designsystemet.slack.com/archives/C07K7NEKXEW/p1726745135430249

**Comment by mimarz** [comment]
> Også relevant: https://designsystemet.slack.com/archives/C07K7NEKXEW/p1726745135430249 ...skal vi prøve å unngå `useContext` helt der mulig?

Why not both? 

Men ja, det var derfor jeg opprettet dette issuet slik at vi kan iterer på `.Context` tilnærmingen, om den fortsatt føles grei eller ikke. 

Da vi snakket om det [første gang](https://github.com/digdir/designsystemet/issues/2221#issuecomment-2339897367) så trodde jeg vi skulle flytte hele contexten opp til `.Context` komponenten. Da fikk et tydelig indikasjon på hvor konteksten er og om du ikke bruker den så må du wire-up ting selv + støtte for react server components.

**Comment by mimarz** [comment]
En annen ting som vi må undersøke er om det finnes komponenter som aldri kommer til å fungere uten React Context og hvordan vi stiller oss til det.

**Comment by mimarz** [comment]
Have a look at this after #1943 and #2508
