### ISSUE TITLE
Create a Baseline CSS file

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2454]
Create a `baseline.css` that defines the default global values for Designsystemet in CSS.

- Move default `color` to global, instead of individual typgography elements (which was a side-effect of old css-modules)
- Suggest moving the content of `ds-rest.css` or rename it to just `reset.css` and import it.
- We have a "bring our own font" approach, do we still want to define a default `font-family` and expect people that want to overwrite or not?
  - One problem I see is our need for `font-feature-settings: 'cv05' 1;` setting that could interfere with other fonts.

Global `color` should be defined as:
```
[data-color="light"], :root { color: ... }
[data-color="dark"] { color: ... }
```

Notes:
- https://wiki.csswg.org/ideas/mistakes

**Comment by eirikbacker** [comment]
Great! Support the initiative! 
Suggestion: remove `ds-reset.css` entirely.
I know we have `box-sizing: border-box` set up for all components here, but I suggest we rather move `box-sizing: border-box` into the individual component files, as this today is a "transparent" dependency which both makes it less explicitly defined when reading each components CSS file, and it depends on all classnames starting with `ds-` which might not be the case if moving to CSS modules or other form of versioning the CSS

**Comment by mimarz** [comment]
> Great! Support the initiative! Suggestion: remove `ds-reset.css` entirely. I know we have `box-sizing: border-box` set up for all components here, but I suggest we rather move `box-sizing: border-box` into the individual component files, as this today is a "transparent" dependency which both makes it less explicitly defined when reading each components CSS file, and it depends on all classnames starting with `ds-` which might not be the case if moving to CSS modules or other form of versioning the CSS

Ah yes! Good point on the `box-sizing`, I knew I forgot someting. I always like to refer to https://wiki.csswg.org/ideas/mistakes for when making new baselines/resets.

**Comment by Barsnes** [comment]
closing this as completed in #2588
