### ISSUE TITLE
Radiobutton ser rar ut ved print i visse nettlesere

### ISSUE THREAD

**Issue by bjosttveit** [digdir/designsystemet#2464]
### Description of the bug

Opprinnelig issue relatert til bruk av PrintButton i app-frontend: https://github.com/Altinn/app-frontend-react/issues/2464

I visse nettlesere kan man ikke se prikken på den valgte radio-knappen når man bruker nettleseren sin print-funksjon.

Bruker som meldte inn opplever problemet i chrome og edge på windows. Jeg fikk ikke problemet i chrome eller firefox på mac, men fikk noe lignende i safari. Merkelig nok så så den helt riktig ut når jeg aktiverte print-css i utviklerverktøyet i safari 🤷 
![bilde](https://github.com/user-attachments/assets/e97855db-b10c-4024-a0e8-3d9238f3ded8)

### Steps To Reproduce

1. https://storybook.designsystemet.no/?path=/docs/komponenter-radio--docs
2. Kryss av
3. Print i nettleser
4. I visse nettlesere ser man ikke prikken, bare litt annen farge på sirkelen

**Comment by mimarz** [comment]
Takk for at du rapporterer dette! Setter veldig pris på det ❤️

Vi har fikset dette i kommende V1 versjonen (`@next`). Vi har dog gjort så mange endringer på tvers av Designsystemet (som du ser har `Radio` fått nytt design) at gjeldende beta-versjon er frøset for å unngå masse konflikter. 

Beklager at vi ikke får fikset det nå, men vi jobber så fort som mulig med å få ut V1!

![Image](https://github.com/user-attachments/assets/e2bf48cb-a5ee-4b75-9d5f-70f897b7f171)

**Comment by mimarz** [comment]
Closing this as we have fixed this in upcoming v1.0.0 (`@next`)

**Comment by Magnusrm** [comment]
@mimarz It seems like this has been re-introduced at some point. Tested in storybook and in our apps with version 1.0.6

<img width="699" alt="Image" src="https://github.com/user-attachments/assets/d2119266-a252-4d63-bdfa-5ba1c927410d" />

**Comment by mimarz** [comment]
> [@mimarz](https://github.com/mimarz) It seems like this has been re-introduced at some point. Tested in storybook and in our apps with version 1.0.6
> 
> <img alt="Image" width="699" src="https://private-user-images.githubusercontent.com/32294735/458742798-d2119266-a252-4d63-bdfa-5ba1c927410d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA4MzU5MDcsIm5iZiI6MTc1MDgzNTYwNywicGF0aCI6Ii8zMjI5NDczNS80NTg3NDI3OTgtZDIxMTkyNjYtYTI1Mi00ZDYzLWJkZmEtNWJhMWM5Mjc0MTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjI1VDA3MTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOGI0OGFlYTQzYzJmOWEzOTVmYjdjYzAwZjc3YWQ5MjE0NjFmYTMxZDc4MGIzYTQ0OTQ0YTJmY2E1MzY0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4Sq_Brflu_PkVkdLF1wHYCQcforWnY_5V6M4e6cJr4Y">

Can you make a new bug issue? What causes this remains to be investigated as tings have changed in the component 🙏
