### ISSUE TITLE
Move box-sizing to each components css file

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2498]
Now `box-sizing: border-box` is set in `.ds-reset`.
This has some issues:
- If class names are hashed in the future (CSS modules) for CSS versioning, the `[class^="ds-"]` will break
- If using CSS without React, a consumer can add  `class="my-button ds-button"`, making `[class^="ds-"]` break
- It is a "transparent" dependency - meaning a developer can not open i.e. `button.css` and see the complete styling
Even though this means repeating `box-sizing` in several files, it is a more robust and explicit solution

**Comment by eirikbacker** [comment]
Awaiting until PRs  onModal, Pagination and Card are merged ☺️
