### ISSUE TITLE
Move `spacing`and `sizing` to dimension tokens type

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2526]
Having both spacing and sizing can be confusing. It is all sizes after all. Token Studio has added dimension token that are closer to the Token definition defined by W3C. We should consider moving over to using them instead. [Token studio documention](https://docs.tokens.studio/token-types/token-type-dimension)

```[tasklist]
### Tasks
- [x] Create new size scales using dimensions
- [ ] Should `border-radius` move into dimensions?
- [ ] Figma changes
- [x] CLI?
```

**Comment by mimarz** [comment]
This is already supported in the CLI. I changed it to check on the path, aka token group name instead of type.

**Comment by mimarz** [comment]
This was done in #2688

Creating a separate issue for merging sizing and spacing design-tokens.
