### ISSUE TITLE
Simplify our form input designs

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2561]
All `inputs` will soon be one component with different types in code. For exampple `input type=text`. This means they will all use the same component tokens in code. To day we are handling states different on different components. Can we make them simpler and more alike? 

- [ ] What is different between our form components today? 
- [ ] What can be simplified? 
- [ ] new read only design

**Comment by mrosvik** [comment]
Investigate: Should we have hover state on input components?

**Comment by eirikbacker** [comment]
Simplifications for our input components:

**Skip using hover:**
- Hover is usually not provided on input elements - both textual inputs and toggle inputs such as radio, checkbox and switch
- Input elements often cover large areas of an application, meaning a hover would produce visual distraction when the user just moves the pointer around in the interface
- Furthermore, hover (especially hover border) often comes in conflict and confusion with the many states an input already have (focus, invalid, checked, etc.)
- Hovering the label of an input, will automatically ad hover-style for the input itself (this is natively done by the browser), but if the label and input have some distance between them, this means the user will have hover-flickering when moving the cursor between label and input
- Our input components already have a complex range of component tokens, and removing hover will simplify the component structure quite a lot - making it easier for our consumers to adjust colors to match their needs.
- Examples of design systems that does not provide input-hover: [GOV.uk](https://design-system.service.gov.uk/components/checkboxes/), [Radix](https://www.radix-ui.com/themes/docs/components/checkbox), [IBM](https://react.carbondesignsystem.com/?path=/story/components-checkbox--default), [Det Fælles Designsystem](https://designsystem.dk/komponenter/tjekboks/, [Salesforce](https://www.lightningdesignsystem.com/components/checkbox/#site-main-content), [Bootstrap](https://getbootstrap.com/docs/5.0/forms/checks-radios/), [Adobe Spectrum](https://opensource.adobe.com/spectrum-web-components/components/checkbox/), [Microsoft Fluent 2](https://fluent2.microsoft.design/components/web/react/checkbox/usage), [Github Primer](https://primer.style/components/checkbox/react/alpha)

**Skip changing border-width on invalid:**
- Changing the border-width on invalid components requires combining `border`+`box-shadow`, as changing the border width will actually change the size of the input, which might cause unwanted layout changes.
- Combining `border`+`box-shadow` only on invalid creates a more complex component token structure, and does also generate some rendering issues as both `border` and `box-shadow` receive the same `border-radius` and thus causing some half-pixel glitches in the edges
- Adding `box-shadow` to the input comes in conflict with focus-styling, meaning increased invalid border will not render when element is focsed
- Increasing border on invalid causes inconsistent input behavior, as only text inputs can get the increased border-width on invalid anyway, as our toggle inputs (checkbox/radio/switch) already have `2px` border
- The change of border-color and even border-width is not sufficient indication that the input is invalid accessibility wise anyway, meaning all invalid inputs must always be accompanied by a `ValidationMessage`. This element will in other words be the most prominent visual indication that a input is invalid - not the change of border-width

**Switch adjustments?**
- Today, switch is the only form element that renders same background color as border color.
- This creates inconsistency in the design logic, and thus also creates the need for more component tokens than if the switch had a white background with border-colored knob/circle matching the color logic of checkbox/text/radio.
- In CSS, `border-color` and text `color` only accepts plain color fills, whereas `background` on the other hand accepts more advanced features like `linear-gradient`, `url` (image) etc. By re-using `border-color` as background-color, we remove the ability for the consumer to change background to something more complex, even though it is technically supported.
- Would it be an alternative to style checkbox like Microsoft does? See example below:
<img width="214" alt="image" src="https://github.com/user-attachments/assets/7fb07a83-00f8-4bfc-bcb3-7fe187f9dbc1">

**Comment by mrosvik** [comment]
After reviewing several sources, reaching out to GovUK, asking UX-Norge community and frontend-forums, we have not found any relevant arguments supporting the idea that input elements should have a hover state for accessibility reasons. The risks associated with having a hover state for input fields are potentially larger, as it can interfere with focus and active states. Therefore, we have decided to remove the hover state for input elements in V1. We will allow the discussion to continue, to see if we gain further insights into which types of users might find hover either a disadvantage or an advantage, and if it does benefit some users, what do they consider a good hover state for input elements?

https://github.com/digdir/designsystemet/discussions/2632

**Comment by mimarz** [comment]
We decided on daily today to also skip changing border-width on invalid ✅

**Comment by eirikbacker** [comment]
Closing this as switch questions is moved to #2664
