### ISSUE TITLE
SkipLink produces invalid HTML when used within a paragraph (<p> cannot appear as a descendant of <p>)

### ISSUE THREAD

**Issue by unekinn** [digdir/designsystemet#2574]
### Description of the bug

The SkipLink documentation in Storybook demonstrates the problem. The following error message is shown in the console:
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
p
a
SkipLink
p
Paragraph
div
...
```

### Steps To Reproduce

1. Run the Storybook locally
2. Go to http://localhost:6006/?path=/docs/komponenter-skiplink--docs
3. Open the console
4. Observe the error message

**Comment by Barsnes** [comment]
Our skiplink does perhaps not need to use a paragraph? 🤔 
I don't see this being a huge issue outside of our stories, but I propose we change the markup of the skiplink to tjis:
```tsx
<a>
  <span>...</span>
</a>
