### ISSUE TITLE
intermediate checkbox should have same width as checked

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2587]
Our Intermediate checkboxes have a different width then our "check" icon on the same component. This was a choice made by me as I thought the intermediate state looked weird with a thin line. And I still think it looks a little thin. 

**This is how it is today**

<img alt="As is" src="https://github.com/user-attachments/assets/22c2e8e0-1994-485f-bb2e-89b377bb0ff0">

The easy fix is to set the intermediate states to the same width as the checked checkboxes. This looks of to me 🤔 I also find that our checkboxes has "smaller" weight then our radio buttons. 

<img  alt="Fixed" src="https://github.com/user-attachments/assets/9dcfb2fe-dd8b-4625-9a4d-b5820b9f5c9a">

To try and fix this I made _chunky check™_ I made the check smaller and chunkier. The intermediate follows the width of the check, but do not have full pill form. (The left side is the new design)

<img alt="Nytt chunky forslag" src="https://github.com/user-attachments/assets/654ca83a-f500-4218-a2ac-8272e7a4f467">

Here it is with our radio buttons. I think they look more in balance. 
<img alt="Med radio" src="https://github.com/user-attachments/assets/72f2a97b-3ff5-4f55-8439-04119e2e432d">

I have some reservations. 
- [ ] Do they fit the style of our component library. Chunky gives of a more childish vibe, and if you use `0` border-radius on other components I think this will look a little off. 
- [ ] Are they harder to see in the squint test? 
- [ ] Any other suggestions, we should try?

**Comment by eirikbacker** [comment]
In #2550, the icon is rendered a bit thinner - verified by Lasse. But, we also give the consumer ability to change stroke width if the want to :)

**Comment by eirikbacker** [comment]
New design possible to inspect on https://storybook-5g3dadjsv-designsystemet.vercel.app/?path=/story/komponenter-input--checkbox - should be aligned with this Figma @Febakke ? ☺️
