### ISSUE TITLE
Fix spinner stroke "overflow"

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2605]
See our spinner in Storybook to see visual bug.

**Comment by Barsnes** [comment]
Noticable on button
![image](https://github.com/user-attachments/assets/0d573fd2-60e8-4f8e-8163-273c9957a35e)

**Comment by Barsnes** [comment]
I was not able to solve this, but we have a new design for spinners in buttons to support all colors, making this issue not as relevant.

**Comment by eirikbacker** [comment]
Closed as both track and line now is same color and thus artifact is not visible anymore :)
