### ISSUE TITLE
`data-ds-color-mode="auto"` no longer works in storybook

### ISSUE THREAD

**Issue by Barsnes** [digdir/designsystemet#2690]
This seems to only be an issue storybook.
This is me checking my color-scheme when in storybook:
![image](https://github.com/user-attachments/assets/acfc1ebf-96ad-496d-9f41-51ac2feb2180)

This is on any other page:
![image](https://github.com/user-attachments/assets/d6fe067f-d8ce-46b5-8467-81d654d285cc)

It seems like this is caused by us setting `color-scheme: light` on `:root`

**Comment by mimarz** [comment]
I suspect it has to do with Storybook using `iframe` for its docs/stories thats messing with getting the correct `prefers-color-scheme`? 🤔

**Comment by mimarz** [comment]
This was fixed by adding a custom ident to iframes inside Storybook, `color-scheme: auto;`
