### ISSUE TITLE
Combobox: Search matching text _inside_ options, not just the beginning of them

### ISSUE THREAD

**Issue by olemartinorg** [digdir/designsystemet#2720]
### Description

Tracking issue:
- https://github.com/Altinn/app-frontend-react/issues/2506

**Comment by Barsnes** [comment]
Hi, you can set a custom filter function using the prop `filter`:
```tsx
<Combobox 
  filter={(inputValue, option) => option.value.toLowerCase().includes(inputValue.toLowerCase())}
/>
```
This is called for every option with the current input value, and an option object:
```ts
type Option = {
  value: string;
  label: string;
  displayValue?: string;
  description?: string;
};
```
