### ISSUE TITLE
Misaligned number centering in `Badge` on Firefox

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2742]
## Description
The number in the `Badge` component appears slightly off-center when viewed in Firefox. This issue seems to be browser-specific, as the alignment looks correct in Edge.

![Image](https://github.com/user-attachments/assets/53137d24-82f0-4069-9268-5c9d62c954a5)

## Steps to Reproduce
Open the Badge component in Firefox.
Compare the centering of the number with how it appears in Edge.

**Expected Behavior**
The number should be perfectly centered in the Badge component across all supported browsers.

**Actual Behavior**
The number in the Badge component is misaligned in Firefox.

## Suggested Solution
Investigate and adjust CSS properties to ensure consistent alignment across browsers.

**Comment by mimarz** [comment]
Tested with version `1.0.0-next.41` and `Badge` number centering seemed to look fine. 

<img width="956" alt="Image" src="https://github.com/user-attachments/assets/1070a19e-f356-46bc-add8-9529916d6abe" />
