### ISSUE TITLE
Affix

### ISSUE THREAD

**Issue by eirikbacker** [digdir/designsystemet#2748]
- Do not set `width: fix-content` unless `[size]` is set on input
- Use single element:
```
<div class="ds-affix" data-suffix="" data-prefix="">
</div>
```

**Comment by Barsnes** [comment]
If we use `data-prefix/affix`, this makes it harder for our consumers to put icons in their affixes, which I could see some people doing.

**Comment by mrosvik** [comment]
18.nov daily: 
@unekinn @Febakke @Thunear @mrosvik @Viveca24 @Barsnes 
We should support svg/icons to serve as visual cues in specific scenarios.
