### ISSUE TITLE
Missing ValidationMessage in `Checkbox` (Figma)

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2762]
In Figma `radio` has an option to turn on "ErrrorMessage", but `checkbox` do not have this option. Should there be an ErrorMessage-option in `checkbox` as well?

```[tasklist]
### Tasks
- [ ] Add ValidationMessage as ComponentProperty to Checkbox in Figma
- [ ] Update the TestPage with errormessage on Checkbox
```

**Comment by Viveca24** [comment]
In the Storybook, I see that the `checkbox` component already includes an "ErrorMessage" message. I have created a boolean value in Figma to toggle the ErrorMessage, just like in the `radio` component.

![Image](https://github.com/user-attachments/assets/022e6677-6b22-492c-b582-01f4512fc1f2)
