### ISSUE TITLE
`Search` component contains a div for error message when there is no error

### ISSUE THREAD

**Issue by standeren** [digdir/designsystemet#2765]
### Version number

0.63.0

### Description of the bug

In version 0.63.0 there is a small issues with the `Search` component.
It contains a div for error message when no error exists making spacing around it inconsequent.

See Image:
![Skjermbilde 2024-11-11 kl  10 21 53](https://github.com/user-attachments/assets/fedafce0-2ffb-44d6-86ea-1a57cd0eea4c)

### Steps To Reproduce

1. Use the component and see that there is a div where the error message can be shown

**Comment by Barsnes** [comment]
Hi, and thanks for the issue!
I am closing this, since it is fixed in next. 

As a solution to your problem, you could remove the gap manually, or change the style in some other way.
