### ISSUE TITLE
Focus outline does not adjust automatically to button width when text expands

### ISSUE THREAD

**Issue by Viveca24** [digdir/designsystemet#2766]
**Description:** In Figma, when the text within a button expands, the focus outline does not adjust accordingly to encompass the full button width. This leads to a visually incorrect focus state, especially in cases where text length changes dynamically or when translated into languages with longer words.

**Expected Behavior:** The focus outline should automatically adjust to the button width to cover the entire button regardless of text content length.

Steps to Reproduce:
1. Use the search component in Figma
2. Set state to active
3. Change the text in the button so it is longer than the default.
4. Observe that the focus outline does not expand to match the button width.

![Image](https://github.com/user-attachments/assets/d95bce8d-4097-4b25-900e-9d8975b7c994)

**Comment by Febakke** [comment]
Will be fixed in #2506
