### ISSUE TITLE
Switch Large does not behave the same way as Switch Medium and Small in Figma

### ISSUE THREAD

**Issue by Viveca24** [digdir/designsystemet#2769]
The Switch Large component does not adjust the width of the description to match the length of the label, unlike Switch Medium and Switch Small. With Switch Medium and Switch Small, the description width dynamically adapts to the label length, but this does not occur for Switch Large. This issue affects only the left label option, not the right.
 
The Switch Large component’s description width should adapt to the length of the label in the same way as Switch Medium and Switch Small, ensuring consistent behavior across all switch sizes.
 
Steps to Reproduce:

1. Use the switch component in Figma in small and large siize.
2. Set the label position to "left."
3. Add a label with varying lengths to each size. Add description as well. 
4. Observe the description width for each switch size.

![Image](https://github.com/user-attachments/assets/3a3b662f-8a1d-4893-98e2-2c639848173e)

This issue also causes problems in our test file. When we detach instances, `Switch Large` appears visually different from the instances, with the description text breaking at an earlier point than expected. This inconsistency complicates visual testing and makes it harder to ensure uniformity across designs.

**Comment by Febakke** [comment]
Should be fixed in Figma now. 
Text element in description was set to fixed. Changed to hug

**Comment by mrosvik** [comment]
LGTM! :D
