### ISSUE TITLE
Remove Brand-option

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2770]
The storefront includes a "Brand" selection button under "Colors" that allows users to choose between four specific brand palettes. This selection option has proven to be confusing, as it only displays a limited set of brands, which may not be relevant for all users.

To simplify and improve the user experience:

Remove the "Brand" selection button entirely from the storefront under "Colors." Set the Digdir palette as the default color palette displayed, as it is the one currently used on designsystemet.no. We dont need to specify that the colors are Digdir colors. 

Acceptance Criteria:
- The "Brand" selection button is no longer visible in the storefront under "Colors."
- The Digdir palette displays by default without a need for user selection.

![Image](https://github.com/user-attachments/assets/59162344-cf2d-4d2b-a63a-185fdcab6163)
https://www.designsystemet.no/grunnleggende/designelementer/farger

**Comment by Barsnes** [comment]
Why should we remove this? It is what comes from our package `@digdir/designsystemet-theme`
