### ISSUE TITLE
Figma file defaults to wrong border-radius when using wrong custom theme

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2861]
Bug filed from user in DM on slack.

Tested together via teams.

When using custom theme: https://next.theme.designsystemet.no/?accent=%231d5f4a&brand1=%233a8a79&brand2=%23d9771a&brand3=%238a4f8d&theme=light&neutral=%234d4d4d

Bug: 
**Using github and Token Studio, after syncing in Figma, `border-radius-default` is referenced to `border-radius-full` instead of `border-radius-4`**

Notes:
- design-tokens json had the correct references so something with how sync settings was used maybe?

**Comment by mimarz** [comment]
We will test this again to try an reproduce. Suspect it has to do with different settings in Token Studio when exporting to Figma. Maybe the remove all variables without links?

**Comment by Febakke** [comment]
I was not able to recreate this. The variables and tokens are correctly referenced and im not sure how this is possible without something happening when exporting tokens to variables in Figma and a connection being broken at some point. 

I think we should close this @mimarz
