### ISSUE TITLE
New component: Card

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#317]
## Related information and insight
- [Material design](https://m2.material.io/components/cards)
- [W3C design system](https://design-system.w3.org/components/cards.html)
- Card i [Entur designsystem](https://design.entur.no/komponenter/layout-og-flater/card)
- Card i [Equinor design system](https://storybook.eds.equinor.com/?path=/docs/surfaces-card--docs)
- Card i [US Gov Design system](https://designsystem.digital.gov/components/card/)

## Card
The card component can be used when you need to present related information or collections of items.  Each card can represent an individual item within the collection, allowing users to scan and interact with them independently. Cards provide a clear visual boundary around content, making it easier for users to perceive and comprehend the information presented.

### Card specification
- The size of the card should be adaptable to different content sizes
- The card should support various types of content: ........
- Consider if the card should support brand-colors and custom alignment.
- We should consider options for truncation long text or expanding the content if it exceeds a certain length.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/572
- [ ] https://github.com/digdir/designsystem/issues/574
- [ ] https://github.com/digdir/designsystem/issues/1114
- [ ] https://github.com/digdir/designsystem/issues/631
```

**Comment by mrosvik** [comment]
Takk for deling @Camulos ! 🙌 🤩

Noen kommentarer til komponenten i BR-figma:
- Det er veldig mange ulike varianter av card her. Det de har felles er kanskje kun skyggen? 
- `Card: Notification-card`: Blir det den samme som `Alert`-komponenten? 🤔
-`Card: Info-box` ligner mye på `accordion`-komponenten, kanskje den samme? 🤔

Vi bør nok se på et `BaseCard ` som flere typer cards kan bygges oppå. Ser at flere designsystem har 
en NavigationCard-variant der hele kortet er klikkbart, og så gjerne en annen variant med statisk tekst/bilde + en eller flere klikkbare knapper i bunnen.

Eksempel på cards fra Digdir: 
<img width="1049" alt="image" src="https://github.com/digdir/designsystem/assets/1464915/ad7ac623-d817-4bf2-83eb-85de0ae15d41">

**Comment by Camulos** [comment]
@mrosvik 
Card: Notification-card blir samme som Alert.
Card: Info-box kan nok på noe vis være liknende accordion, her er den slik den er i bruk:
<img width="1167" alt="Skjermbilde 2023-06-20 kl  10 36 55" src="https://github.com/digdir/designsystem/assets/5771598/44780f8c-b25e-4457-8df7-6b4e3a6e6d43">

**Comment by Camulos** [comment]
Er den mest grunnleggende varianten av kort da noe ala:

Card (skal som oftest være section, article e.l.)
Header: overskrift og ikon
Footer: metainfo, ekstra info (bør vel være mulig å velge å plassere til slutt i kortet, men semantikken krever ikke det)
Content: en div eller noe som avgrenser hovedinnhold i kortet, kan bruke flexbox e.l. for å få til kolonner.

Støtte for bilde del av header eller som en div over header muligens?
Header og Footer forutsetter at kortet er en type element som tillater det (feks section).

**Comment by framitdavid** [comment]
Mange fine tanker og innspill her! 👏 🤩 

Det stemmer det @Camulos sier om at ofte så ønsker man `<article/>` eller `<section/>` som semantisk element type for kortet, men ikke nødvendigvis alltid at man ønsker det. Felles Designsystem burde ikke låse kortet til å være enn av disse to elementene, men heller være mer fleksible. Her kan vi vurdere om denne komponenten er en kandidat for _polymorphism component_. Det betyr at vi kan fortelle komponenten hvilket element vi ønsker at Card skal rendre som native-element. Det kunne eksempelvis sett noe sånn her ut: `<Card as="section">` eller `<Card as="article"/>` eller `<Card as="div"/>`. Dette vil kunne åpne for at andre enkelt kan bruke den riktige semantiske elementet sitt use-case.

Videre tenker jeg at vi må også finne ut hvordan vi skal eventuelt løse det med innholdskomponenter som heading og footer. Vi burde komme frem til en løsning som også er fleksibel som ikke begrenser komponenten mer enn nødvendig. Jeg mener at det er viktig at komponentene som vi lager i Felles Designsystem er åpne for utvidelse, med det mener jeg at det skal være lett for andre å lage sin egen interne CardComponent som bygger videre på den vi har i Felles Designsystem. Eksempelvis deg @Camulos, hvis du trenger noe mer enn basen vi kan tilby, så skal du enkelt kunne bygge videre på den vi har uten å måtte gjøre endringer hos oss internt i Felles Designsystem. 

Jeg har troen på at vi i Fellesskap skal kunne finne en god løsning på hvordan dette burde løses. Jeg skal ta en titt på andre biblioteker og se hvordan de har løst det. 👍

**Comment by hannekristin** [comment]
Vi i autorisasjon har behov for kort. En variant tar deg til en ny side, mens den andre åpner seg på siden man er på. 
![image](https://github.com/digdir/designsystem/assets/103100644/e53a4157-55fc-4ea8-b741-ea39752fe31f) 
![image](https://github.com/digdir/designsystem/assets/103100644/98e15625-208b-4865-be83-a78890209ba6)

**Comment by Camulos** [comment]
`<card as section, article, div>
(image, tags, icons)
<card-header as header, div>
	(image, title, sub-title, icon)
<card-header>
<card-footer (alt1) as footer, div>
	(card-meta date, author, tags, icon)
<card-footer>
<card-content as div>
	(paragraphs, headers, links, columns, lists, CTA-button, buttons, links, icon, image)
<card-content>
<card-footer (alt2) as footer, div>
	(card-meta date, author, tags, icon)
<card-footer>
(image, tags icons)
<card>
`

Mulighet for å
rendre som section, article eller andre semantiske objekter
rendre header og footer som header/footer når semantikken tillater det
plassere footer rett etter header eller etter innhold
tillate opp til flere kolonner inne i innholdsområdet for desktop-visning
bilder i eller utenfor de semantiske elementene
flere CTAer (feks 3 knapper eller flere lenker)
