### ISSUE TITLE
🎯 Visjon og mål

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#340]
# Visjon / Overordnet mål: 
Vårt ønske og ambisjon er at felles designsystem kan bidra til at innbyggerne i Norge i større grad opplever «én digital offentlig sektor».

Gjennom å samarbeide om et felles designsystem kan vi i større grad sikre helhetlige brukeropplevelser og universell utforming.

# Hovedmål og delmål

## ✹ Felles designsystem i Digdir
- Forstå eksisterende design i ulike produkter
- Identifisere behov som går igjen på tvers
- Hvilke designelementer, komponenter og mønstre gir det mening at gjenbrukes på tvers

### ✧ Sluttbrukeren skal oppleve de tjenestene Digdir bidrar til som mer helhetlig
- Vi skal bruke felles grunnleggende designelementer
- Vi skal bruke felles grunnkomponenter 
- Vi skal etablere gjenkjennbare interaksjonsmønster som går igjen på tvers av tjenester og produkt.
- Vi skal delta i brukertester som blir utført i produktteamene der designsystemet er i bruk. 
- Vi skal basere fundamentet på bred brukerinnsikt, fra flere deler av offentlig sektor, og på [designprinsippene](https://docs.altinn.studio/nb/app/design/guidelines/design-principles/) våre.

### ✧ Produktteam i Digdir skal bruke designsystemet i sine produkt.
- Vi skal samle behov fra de ulike produktteamene i Digdir.
- Vi skal tilrettelegge for hospitering i Designsystem-teamet og hjelpe andre å ta det i bruk og bidra til utviklingen.
- Vi skal være åpne og transparente for å vise hva vi jobber med og hva som kan være gjenbrukbart for andre.
- Vi skal jobbe for at produkteeiere tar med designsystemet som en del av produktutviklingsprosessen.

### ✧ Designere i Digdir skal enkelt kunne finne og bruke styles, grunnkomponenter og retningslinjer.
- Vi skal lage et godt oversiktlig bibliotek i Figma av komponenter og styles
- Designsystemet skal være "the single source of truth"
- Gjennom å oppgradere til Figma Organization, skal vi tilrettelegge for bedre flyt mellom designsystemet og produkt-filer.
- Vi skal dokumentere relevant informasjon etter research og brukertester som angår konkrete komponenter og interaksjonsmønstre.
- Brukerteste oppsett og dokumentasjon mot designere i Digdir

### ✧ Utviklere i Digdir skal enkelt kunne finne og bruke grunnkomponenter og styles.
- Vi skal eniges om felles grunnprinsipper for kode, arkitektur, versjonering, navnekonvensjoner, styles, komponenter, osv
- Vi skal tilgjengeliggjøre komponentene via npm-pakker og dokumentere den tekniske delen i Storybook
- Brukerteste oppsett og dokumentasjon mot utviklere i Digdir

### ✧ Tjenesteeiere i Altinn skal kunne forstå hvordan og når ulike komponenter skal brukes.
- Vi skal tilby god dokumentasjon og eksempler for hvordan komponenter skal brukes og ikke.
- Altinn Studio skal lenke til relevant dokumentasjon per komponent.  
- Høy tillit: Designsystemet skal oppleves som inkluderende, transparent, tidsbesparende og av god kvalitet.
- Brukerteste oppsett og dokumentasjon mot tjenesteeiere i Altinn.

## ✹ Felles designsystem på tvers av offentlig sektor
- Andre deler av offentlig sektor skal bruke og bidra til å designe og bygge opp felles designsystem. 
- Designsystemet skal bli en samarbeidsarena der vi sammen jobber for at ⭐️ innbyggerne skal oppleve offentlige tjenester mer helhetlig ⭐️

### Parallelle aktiviteter:
✧ Vi skal invitere til samarbeidsarenaer rundt felles designsystem
✧ Vi skal dele vår ambisjon blant alle interessenter
✧ Vi skal tilrettelegge og fasilitere for designsystem-samarbeid på tvers av offentlig sektor
✧ Vi skal utforske en tverretatlig arbeidsgruppe
✧ Vi skal jobbe for mer ordnede rammer i det offentlige for å kunne jobbe på tvers på denne måten med et felles mål. 

# Suksesskriterier
- Forankring i Digdir 
- Forankring i det offentlige (KDD)
- Samfunnsøkonomisk analyse
- Tydelig og kontinuerlig kommunikasjon uttad
- Høy brukskvalitet

**Comment by mimarz** [comment]
@mrosvik will move this to wiki
