### ISSUE TITLE
Update documentation with expected font family import

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#428]
We should update our documentation in Storybook to informat that we expect users to import their desired font-family in their app and that its not provided in the library. 

- Note about that everything is designed around "Inter" font and its the recommended font to use.
- Note about recommended fallback fonts
- Fix Tokensblock typo

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/458
- [ ] https://github.com/digdir/designsystem/issues/480
- [ ] https://github.com/digdir/designsystem/issues/495
- [ ] https://github.com/digdir/designsystem/issues/912
```

**Comment by Barsnes** [comment]
Where in storybook should this be added?
Maybe we should have a new page wiht setup/usage?

**Comment by mrosvik** [comment]
Github readme covers this.
