### ISSUE TITLE
Wrong option is read out when de-selecting by MacOs VoiceOver on Chromium

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#464]
When using the `Combobox` in `multiple` mode the options read out when selecting and de-select are wrong.

Video of bug (remember to turn on sound).

https://github.com/digdir/designsystemet/assets/1070981/fc6c037a-3407-46e8-871a-d2f91c8f4fc6

**Comment by mimarz** [comment]
We will test for this when new component is developed

**Comment by mimarz** [comment]
This bug is still present on new Combobox. Updating issue with new findings

**Comment by mrosvik** [comment]
This is most likely a problem with VoiceOver, not with the Combobox. The combobox follow W3C requirements.
