### ISSUE TITLE
Add compact mode token transform

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#493]
We need to update the token transformer (style dictionary) to make a new set for "compact mode".

The plan is for this to be a new css file (`compact.css`?) that is to be used alongside `tokens.css`.

The import for our users that wants to use "compact mode" would be something like this.

```tsx
import '@digdir/design-system-tokens/brand/altinn/tokens.css';

import '@digdir/design-system-tokens/brand/altinn/compact.css';
//or
import '@digdir/design-system-tokens/compact.css'; // "Global", if we don't want compact mode to be brand specific
```

**Comment by mrosvik** [comment]
Not relevant anymore, due to new token structure. #1849
