### ISSUE TITLE
Card: Design component in Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#572]
### Design specification: 
........

### Design tasks

- [x] Design is fully specified in Figma
  - [x] Design component with all relevant states
  - [x] Do a accessibility test of the sketches
  - [x] Functionality/animation is described and prototyped if relevant    
  - [x] If there are used any svgs in this component is it available for the developer? [Link]
  - [ ] Link to Figma design: [Link]

**Comment by mimarz** [comment]
@Febakke and @Thuneer will have a look at this and try to decide on first draft1

**Comment by mimarz** [comment]
reopened as we found some new use-cases we had to design for

**Comment by Febakke** [comment]
Review 🔬 
- [ ] Image bug, when i put the card into my file the image would change between different cats. Im not complaining about the cat based slideshow, but it was a bit weird. Maybe if we only have one image in the component this would not happen. 
![Skjermbilde 2024-01-08 kl  14 02 18](https://github.com/digdir/designsystemet/assets/33222679/ecf41457-1ae9-424a-90cf-bc61125cb25d)
- [ ] What would be the best way to scale the cards? Now we get a lot of whitespace at the bottom of the card. I think maybe the footer should be sticked to the bottom?
![Skjermbilde 2024-01-08 kl  14 18 05](https://github.com/digdir/designsystemet/assets/33222679/5437f8a3-c074-4ba5-a0be-d2e4cb7e4b87)


- [ ] Not related to the component, but do we need a guide telling the user how they change the image easily? Its not handled by the component props, so it diverge a little from our other components.

**Comment by Thuneer** [comment]
1. I removed the other images from fill. Looks like they got carried over as I was copying them in.
2. Think we decided to not do anything to support vertical scaling as this would break other functionality within the card.
3. Good idea! I can create an issue on this when I am closing this issue.

@Febakke Let me know if these issues now are fixed, then I can close this issue.

**Comment by Febakke** [comment]
Looks great! Closing this!
