### ISSUE TITLE
Storefront: Add link to edit page in github

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#637]
![Image](https://github.com/digdir/designsystem/assets/1464915/c7190a3f-e6e6-4080-ae59-2b30a2974d66)

**Comment by mimarz** [comment]
This needs to be specified technically how to be implemented

**Comment by mimarz** [comment]
Suggest using our `Link` component for this.

**Comment by mimarz** [comment]
> @mimarz Can we start by linking to the folder `apps/storefront/pages/`? [ref](https://github.com/digdir/designsystemet/tree/main/apps/storefront/pages)

Sure, if thats good enough for @mrosvik ?
