### ISSUE TITLE
Tokens: Disabled state

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#668]
How should we handle colors for disabled components? As of now we use `opacity.disabled` as a general token for this state. This makes sense in Figma, but might not be the best solution in code. Also will change depending the background color. 

**Possible solutions**
Change to two subtle neutral colors.
Suggested colors:
`semantic.surface.neutral.subtle`
`semantic.border.neutral.subtle`

**Comment by mrosvik** [comment]
Opacity ble brukt for å beholde ulike farger, se f.eks button. Men mulig det ikke gir noe verdi med farger på disabled state uansett. Vi kan diskutere det når du er tilbake :) 

![Image](https://github.com/digdir/designsystem/assets/1464915/50ce813e-c787-4e17-bc3a-0fbba15516be)

**Comment by mimarz** [comment]
Using opacity will make background colors "bleed" through the button, giving a bit different look depending on background.

![image](https://github.com/digdir/designsystem/assets/1070981/4945e177-d09a-4f0e-a526-a4b4d15f91bf)
![image](https://github.com/digdir/designsystem/assets/1070981/8fe0d6dc-214d-4e86-9aa8-0ceae91e8346)
![image](https://github.com/digdir/designsystem/assets/1070981/1193adca-a879-4c5b-9d53-1aff87efadf5)

**Comment by mrosvik** [comment]
It is done by both UK Gov:

<img width="1633" alt="image" src="https://github.com/digdir/designsystem/assets/1464915/1160be2e-b1e2-4de5-912f-aa82a3d769bc">

And Nav: 

<img width="1465" alt="image" src="https://github.com/digdir/designsystem/assets/1464915/4d9560eb-5c25-4311-8e1a-1924af97f0a6">

**Comment by Febakke** [comment]
We have decided to use the opacity aproach on our disabled states
Figma change handled in #1204 

Close this? @mrosvik @mimarz

**Comment by mimarz** [comment]
Will update react components in #1327
