### ISSUE TITLE
Decide which tokens should be used on input components

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#738]
Vi should decide if text-field, text-area, select, radio, checkbox should use action-dark og input-default 

![Image](https://github.com/digdir/designsystem/assets/1464915/40276b92-5e48-4020-908c-41f7fc3e58df)

**Comment by mrosvik** [comment]
Vi should decide if text-field, text-area, select, radio, checkbox should use action-dark og input-default 

![Image](https://github.com/digdir/designsystem/assets/1464915/40276b92-5e48-4020-908c-41f7fc3e58df)

**Comment by mimarz** [comment]
Is this longer relevant with #1259 ? @mrosvik
