### ISSUE TITLE
Table: Design component in Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#795]
## Update
We have started making an example component based on the tables found in Altinn 3 apps. This component is a prototype on how we can build flexible tables in Figma. You can find it [here](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=24926-12697&mode=design&t=ImGSHHZ3D8DGV5jg-0)

## Tasks
- [x] Research tables
- [x] Create design for designsystem version of table

**Comment by mrosvik** [comment]
Looks awesome, great work! 🤩 Can't wait for [this feature](https://forum.figma.com/t/expose-nested-instances-at-property-level/30052/101) from Figma so we can hide some of the nested instances.

**Comment by Edavda** [comment]
Found a small issue with the `header sortable` and `header column` types not displaying the `zebra` property correctly. The background color overflows the cell when toggled on in Figma. 



![Image](https://github.com/digdir/designsystemet/assets/2195512/f313db34-d531-492a-bb43-b3e698a4c637)

**Comment by Febakke** [comment]
@Edavda 
Published a fix now.

But do we need zebra stripes for the headers? 🤔

**Comment by Febakke** [comment]
Removed zebra stripes on headers in Figma. Closing this
