### ISSUE TITLE
Improvements: List

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#80]
## Related information and insight
- See previous lists from [altinn](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=6616%3A25192&t=fgu4e3XDW9eMAE9U-1)
- See previous lists from [digdir](https://www.figma.com/file/rrBqUrSQl6jdAJpjUzV3cN/Komponenter--%7C--Digdir-nettsider?node-id=4254%3A42027&t=y650dzMg7uujBVib-1)
- https://carbondesignsystem.com/components/list/usage/
- https://designsystem.dk/komponenter/strukturerede-lister/

Relevant issues: 
- https://github.com/digdir/designsystem/pull/206 

## Specification and requirements
- _Add specification and requirements_

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/670
- [ ] https://github.com/digdir/designsystem/issues/980
```

**Comment by Barsnes** [comment]
@mrosvik This epic seems to be done, should we close?
