### ISSUE TITLE
New component: Loader

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#81]
### Related issues or relevant information?

- https://aksel.nav.no/komponenter/core/loader
- https://carbondesignsystem.com/components/loading/code/
- https://designsystem.dk/komponenter/spinner/
- https://www.lightningdesignsystem.com/guidelines/loading/

### Requirements/Specification
- Spinner and Skeleton should be two components inside "Loader"
- _Add requirements_

```[tasklist]
### Spinner
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Skeleton
- [ ] Add a draft title or issue reference here
```

**Comment by mimarz** [comment]
This is finished? @mrosvik

**Comment by mrosvik** [comment]
The `Loader` componets are ready for use: https://storybook.designsystemet.no/?path=/docs/felles-list--docs
