### ISSUE TITLE
Next.js App Router and SSR (Server side rendering)

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#817]
### Description of the bug

I have been testing the components with Next.js` new App router, and have discovered some issues:
* None of the components work with SSR. Client side hooks are being used in most / all components and it gives an `React.createContext` error.
* The computed styles from the CSS modules do not work even if the component itself supports SSR. No styles are loaded when the page first loads.
* On a client side component there is an issue where the computed styles from the CSS modules are delayed. The computed styles are not applied on the initial server payload, but on the second pass. This means that there will be a split second where no styles are being applied.

Suggested resolutions:
* Go through the components and make sure they work with SSR by using SSR friendly hooks.
* Change from CSS modules to using a single CSS file directly. This will be sent with the server and work on both CSR and SSR.

### Steps To Reproduce

I created a repo with instructions on how to replicate the issues with a server and a client component:
https://github.com/Thuneer/next-ssr

**Comment by mimarz** [comment]
Related to #862

**Comment by mimarz** [comment]
Correct @Barsnes :)
