### ISSUE TITLE
Versjonering av komponenter i Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#834]
Vi må få på plass rutiner for oppdatering av Figma komponenter slik at oppdateringer blir mest mulig forutsigbart for designere.

**Comment by mrosvik** [comment]
**Møtereferat 19.09.23**
@Febakke @Thuneer @mrosvik 

Vi har sett på hvordan Aksel håndterer dette: https://aksel.nav.no/grunnleggende/introduksjon/versjonering-i-figma 

Vi lurer på om en utviklingstilnærming vil fungere bedre for oss, ved at vi bruker brancher og pusher ut mindre endringer der det som er endret er dokumentert. Ved breaking changes kan vi lage en ny versjon av komponenten.

Tre nivåer av endringer:
- Lage ny komponent: Skjer i eget arbeidsområde og flyttes over til "Felles komponenter" når den er klar.
- Små endringer av eksisterende komponenter: Skjer direkte i eksisterende komponenter.
- Større endringer på eksisterende komponenter: Ny versjon av komponenten lages, gammel komponent fases ut og avpubliseres.

Publisering av nye endringer:
- Minimum en gang i uka
- Hver gang vi publiserer endringer lager vi også en ny versjon i versjonshistorikken i Figma basert på Semantic Versioning, slik at vi har mulighet til å rulle tilbake en versjon. 
- Bruke en [egen testfil med alle komponenter](https://www.figma.com/file/5x3i5T512RVrbUDn8PW4H6/Eksempler?type=design&node-id=2%3A3799&mode=design&t=Sokh27FqHmy672BL-1 ) der vi kan teste at alt ser riktig ut rett etter at ny versjon av "Felles komponenter" blir publisert. Skjer det noe, må vi evt. rulle tilbake.

**Comment by mrosvik** [comment]
Har fått noen nyttige innspill på dette fra en god venn:

- Små endringer av eksisterende komponenter: Skjer direkte i eksisterende komponenter.
> Vi gjør dette i en branch som oftest. Det er lett å glemme arbeidet. Vi vil helst ha en gjennomgang av en annen designer også, – Det er også lettere å avslutte iterasjonen om du har sporet litt av eller ønsker å begynne på ny (slette branchen).


- Publisering av nye endringer:
> Vi publiserer så ofte vi kan for å unngå at designsystemet blir for skummelt. Og for å redusere frykten for å gjøre endringer. Å vente en hel uke kan også føles skummelt, spesielt når endringer blir utført av ulike designere.
> Vi oppfordrer heller våre brukere til å oppdatere i en branch hvis de er usikre på hvilke endringer som vil påvirke deres design. Jeg vet at våres designerne opplever dette som irriterende, det er daglig oppdatering i komponentene. Her er det nok mye mer aktivitet enn hos dere, siden vi jobber med dårlige komponenter som har blitt publisert – komponenter som aldri skulle ha blitt utgitt. Jeg er ikke sikker på hva som er det beste, men personlig mener jeg at designsystemet bør kunne tilpasses og endres jevnlig, heller enn at publiseringsprosessen skal være skremmende eller problematisk.
> 

> I Storybook gjør vi større releaser :high_brightness:
> 
> Tips:
> Figma har også god statistikk over brukte komponenter og hvem som bruker dem. Vi ser alltid på dette før vi gjør større endringer på komponentene og varsler de som kanskje kan bli påvirket av det.

**Comment by mimarz** [comment]
will be looked at after #501

**Comment by mrosvik** [comment]
VI har fått på plass versjonering av filer som pushes til community, og vi lagrer alle endringer i en github issues per release. Endringsloggen lenkes til fra Figma community. 

![Image](https://github.com/user-attachments/assets/5f3deb6a-87b2-43d9-b313-bf02f6938a67)

Figma community changelog: #1299
