### ISSUE TITLE
Storefront: Add package version number indicator to token preview

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#842]
I have gotten feedback several times in DMs of tokens using wrong token names in their code. 

Suggest adding something like a [shield](https://shields.io/) or similar to indicate which package version the respective token preview is for.

**Comment by mimarz** [comment]
We need to have a closer look at this, maybe separate storefront tokens build from tokens

**Comment by Barsnes** [comment]
Should be done after #1570 is merged, since this will change the package name
