### ISSUE TITLE
Improvements: Radio button

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#86]
### Related information and research findings:
- [Radio in Aksel design system](https://aksel.nav.no/komponenter/core/radio)
- Radio in [Entur design system](https://design.entur.no/komponenter/skjemaelementer/radio-button)
- [Radio in Gov UK Design system](https://design-system.service.gov.uk/components/radios/)
- There is a suggestion from OED to expand more information below each radio button: [Expandable radio buttons](https://github.com/orgs/digdir/projects/3/views/1?pane=issue&itemId=18848256)
- https://github.com/digdir/designsystem/issues/563

### Radio specification

- The whole radio button should be clickable (the circle, the gap and the label)
- When there is multiple lines with text, the circle should stay on top (next to the first line). 
- Should use the new yellow focus style
- The label should be using label typography component
- _Todo: add more technical specification_

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/522
- [ ] https://github.com/digdir/designsystem/issues/523
- [ ] https://github.com/digdir/designsystem/issues/524
- [ ] https://github.com/digdir/designsystem/issues/656
```

**Comment by Barsnes** [comment]
All linked issues are closed, should we close this epic?
