### ISSUE TITLE
Offer alternative to `font` shorthand

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#957]
Related to [#922](https://github.com/digdir/designsystem/issues/922)

**Comment by mimarz** [comment]
This is still an issue, event with layers, so prioritising this now.

**Comment by Barsnes** [comment]
When we move away from this, we can set font-family as 
```
[class="ds-"] {
  font-family: ...
}
```

Not sure how this will work with selectors such as `:root` or `body` - but we will have to explore this

**Comment by mimarz** [comment]
`MdxContent` and `TokenSize` in storefront are the only ones using the font shorthand tokens now. All react components either use the typography CSS class or React component.
