### ISSUE TITLE
Test Chromatic for visual testing

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#963]
We have had several bugs due to lack of regression visual regression testing. This will just get worse as component library grows and we make a css library.

Investigate on what options we have in this regard.

Notes:
- https://www.chromatic.com/
- https://docusaurus.io/blog/upgrading-frontend-dependencies-with-confidence-using-visual-regression-testing
- https://percy.io/
- https://loki.js.org/

**Comment by unekinn** [comment]
Since Chromatic is free to get started and I have some experience with it, we're trying it first. The work done in Storybook stories to make visual tests add value is the same regardless of the testing framework.
