### ISSUE TITLE
Figure out correct aria attr for `Popover` and `HelpText`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#995]
We have [aria-haspopup](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup) and [aria-controls](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls) which are normally used in conjunction with dialogs or popups. 

Its however not clear when you should use which one always as it "depends" on the intended content and its interactivity. 
Do some investigation to figure out here which combination are good to use and document the uses-cases so that we can apply this to our components and also teach others.

**Comment by mimarz** [comment]
Related to #210

**Comment by Barsnes** [comment]
References:
https://react-spectrum.adobe.com/react-aria/Popover.html
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/
